//! The install-media hash table: a compiled-in list of known AmigaOS install
//! disks, keyed by content hash, and a lookup that respects the shape of the
//! data rather than the shape a naive reader would assume.
//!
//! `media_hashes.json` is adopted from
//! [`rootrootde/emu68hatcher`](https://github.com/rootrootde/emu68hatcher)
//! (MIT) — 186 rows, fetched 2026-09-06 and **not regenerated by this
//! module**. The file's own `$comment` field carries the same provenance and
//! the same two traps this doc repeats, so a reader who opens the JSON
//! directly is warned too:
//!
//! - **The mapping is hash → disk, and it is many-to-one.** One logical disk
//!   has many dumps — `Workbench3_1` alone carries 11 distinct hashes. A
//!   structure keyed *disk → hash* would be wrong; this module never builds
//!   one. `rows()` is a flat list and `row_for()` looks a single hash up in
//!   it — nothing here assumes a disk owns exactly one hash, or the reverse.
//! - **`version` and `source` are reported as the row states them, never
//!   re-derived.** The `Hyperion (3.2.2.1 Hotfix Pack)` source contributes 29
//!   rows: 28 tagged `version: "3.2.2"` and one tagged `"3.2.2.1"`. That is
//!   the source's own disagreement, not this table's mistake and not this
//!   module's to resolve — `row_for` and `rows` hand both fields back exactly
//!   as stored, and nothing here normalises, corrects or collapses them.
//!
//! This table only answers "which row does this hash match" — it makes no
//! claim about the disk. §4.3 of the design (`docs/superpowers/specs/
//! 2026-09-06-media-identification-by-hash-design.md`) is what governs how a
//! caller may phrase a match; this module just hands back the row's fields.
//!
//! ## Loading, and what happens if the shipped JSON is broken
//!
//! Same shape as `core/distro`'s registry: a JSON file in this directory,
//! `include_str!`-ed in, parsed with `serde_json`.
//!
//! [`rows`] and [`row_for`] originally returned plain data —
//! `&'static [MediaRow]` and `Option<&'static MediaRow>` — with no error arm,
//! on the reasoning that the table ships inside the binary, never changes at
//! runtime, and is already guarded by this module's own invariant tests
//! (`the_shipped_table_has_exactly_186_rows` and the rest below), so a parse
//! failure could only be a defect caught long before a release reached a
//! user. On that reasoning, a broken table simply **panicked** the first
//! time either function ran.
//!
//! **That reasoning was wrong, for the same reason `recipe.rs` documents
//! under "It returns an error and does not panic (fix round 1, F10)".**
//! `panic = "abort"` in the release profile means a panic here does not stay
//! contained to one caller — it takes the whole application down. Shipped
//! data being wrong is still a bug; it should be one that produces a
//! refusal a user can read and a process that is still running, not a crash.
//! So both functions now return [`CoreResult`](crate::core::error::CoreResult),
//! matching `core/distro::profiles()`, which returns a `Result` for exactly
//! this reason.
//!
//! The table is still parsed once, lazily, behind a [`std::sync::OnceLock`]
//! — but what is cached is the parse **result**, not only the success, so a
//! broken table is reported identically on the first call and the
//! thousandth. This is the same arrangement `recipe.rs`'s
//! `shipped_component_overrides` documents under "Parsed once, not once per
//! row": `CoreError` is not `Clone`, so the cache holds the failure as its
//! own text and rebuilds a [`CoreError::Malformed`](crate::core::error::CoreError::Malformed)
//! from it on every subsequent call, with the original error's text
//! unchanged.

use crate::core::error::{CoreError, CoreResult};
use serde::Deserialize;
use std::sync::OnceLock;

/// One row of the table: a single dump's hash and what Emu68 Hatcher's data
/// says about it.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct MediaRow {
    /// 32 lowercase hex characters. Table lookup only — never ART's
    /// integrity hash (that stays SHA-256; see `core/hashing.rs`).
    pub md5: String,
    /// As the row states it. **Not re-derived** — see this module's own doc
    /// comment on the Hotfix Pack disagreement.
    pub version: String,
    /// The AmigaDOS volume name this dump carries — the same value
    /// `core/osinstall/scan.rs` already reads off a real disk's root block.
    pub volume: String,
    /// A human-readable label for the disk, as Hatcher's table names it.
    pub name: String,
    /// Where Hatcher's table says this dump came from. As stated — never
    /// re-derived.
    pub source: String,
    /// The disk's position within its set, when the source states one.
    pub sequence: Option<u32>,
}

/// The shape of the shipped JSON file. `$comment` and `adopted_from` are
/// provenance for a human reader and are not modelled here — an unknown
/// field in the source JSON is simply ignored, not rejected.
#[derive(Debug, Deserialize)]
struct MediaTable {
    media: Vec<MediaRow>,
}

/// The registry as it ships, compiled into the binary.
const MEDIA_HASHES_JSON: &str = include_str!("media_hashes.json");

/// Parses a media table from its JSON text. Split out of [`cached`] so the
/// failure path — otherwise unreachable through the public API, since the
/// compiled-in JSON always parses — has something to call directly with
/// malformed input.
fn parse_table(json: &str) -> Result<Vec<MediaRow>, String> {
    let parsed: MediaTable = serde_json::from_str(json).map_err(|e| e.to_string())?;
    Ok(parsed.media)
}

/// Parses `json` into `cache` on first use and hands back a reference into
/// whatever is already there on every call after. What is cached is the
/// parse **result**, not only the success, so a broken table is reported
/// identically on the first call and the thousandth — see this module's doc
/// comment. Split out of [`table`] so a test can hand it a private
/// `OnceLock` and malformed JSON without touching the process-wide table
/// that every other caller shares.
fn cached<'a>(
    cache: &'a OnceLock<Result<Vec<MediaRow>, String>>,
    json: &str,
) -> CoreResult<&'a [MediaRow]> {
    match cache.get_or_init(|| parse_table(json)) {
        Ok(rows) => Ok(rows),
        Err(detail) => Err(CoreError::Malformed {
            format: "install-media hash table".into(),
            detail: detail.clone(),
        }),
    }
}

/// Parsed once, on first use.
fn table() -> CoreResult<&'static [MediaRow]> {
    static TABLE: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
    cached(&TABLE, MEDIA_HASHES_JSON)
}

/// Every row in the shipped table, in file order. Many rows can share a
/// `volume` — see this module's doc comment on the many-to-one mapping.
pub fn rows() -> CoreResult<&'static [MediaRow]> {
    table()
}

/// The row whose `md5` matches `md5`, if any.
///
/// Case-insensitive on the **input** — a user's own hashing tool may emit
/// uppercase hex — but exact on the **stored** value, which the shipped table
/// already carries as lowercase (asserted by this module's own invariant
/// tests). A hash matching no row returns `Ok(None)`; per §4.3 of the design,
/// that says nothing about the disk's identity and must never be read as a
/// negative claim. `Err` means the table itself could not be read, which is
/// a different situation entirely and must never be collapsed into "no
/// match".
pub fn row_for(md5: &str) -> CoreResult<Option<&'static MediaRow>> {
    let needle = md5.to_ascii_lowercase();
    Ok(table()?.iter().find(|row| row.md5 == needle))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Unwraps [`rows`]'s `CoreResult` — the shipped table always parses, so
    /// every test above the error-path tests below treats a failure here as
    /// a hard test bug rather than something to assert about.
    fn shipped_rows() -> &'static [MediaRow] {
        rows().expect("the shipped table must parse")
    }

    #[test]
    fn the_shipped_table_has_exactly_186_rows() {
        assert_eq!(
            shipped_rows().len(),
            186,
            "expected 186 rows in the shipped table"
        );
    }

    #[test]
    fn every_md5_in_the_table_is_distinct() {
        let hashes: HashSet<&str> = shipped_rows().iter().map(|row| row.md5.as_str()).collect();
        assert_eq!(
            hashes.len(),
            186,
            "expected 186 distinct md5 values, found {}",
            hashes.len()
        );
    }

    #[test]
    fn every_md5_is_32_lowercase_hex_characters() {
        for row in shipped_rows() {
            assert_eq!(row.md5.len(), 32, "'{}' is not 32 characters long", row.md5);
            assert!(
                row.md5
                    .chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "'{}' is not lowercase hex",
                row.md5
            );
        }
    }

    #[test]
    fn every_row_has_its_descriptive_fields_filled_in() {
        for row in shipped_rows() {
            assert!(!row.version.is_empty(), "{}: empty version", row.md5);
            assert!(!row.volume.is_empty(), "{}: empty volume", row.md5);
            assert!(!row.name.is_empty(), "{}: empty name", row.md5);
            assert!(!row.source.is_empty(), "{}: empty source", row.md5);
        }
    }

    #[test]
    fn the_many_to_one_mapping_is_real_not_assumed() {
        // Named per the design's §2.2 measurement, not the brief's guess: a
        // hash → disk table only means something if more than one hash can
        // point at the same disk, and this asserts the actual counts rather
        // than trusting the doc comment above.
        let count_volume =
            |volume: &str| shipped_rows().iter().filter(|r| r.volume == volume).count();
        assert_eq!(count_volume("Workbench3_1"), 11);
        assert_eq!(count_volume("Install3_1"), 11);
        assert_eq!(count_volume("Locale3_1"), 10);
        assert_eq!(count_volume("Storage3_1"), 10);
        assert_eq!(count_volume("Extras3_1"), 9);
        assert_eq!(count_volume("Fonts3_1"), 6);
    }

    #[test]
    fn the_hotfix_pack_disagreement_is_pinned_not_tidied() {
        let hotfix: Vec<&MediaRow> = shipped_rows()
            .iter()
            .filter(|r| r.source == "Hyperion (3.2.2.1 Hotfix Pack)")
            .collect();
        assert_eq!(hotfix.len(), 29, "expected 29 Hotfix Pack rows");

        let tagged_322 = hotfix.iter().filter(|r| r.version == "3.2.2").count();
        let tagged_3221 = hotfix.iter().filter(|r| r.version == "3.2.2.1").count();
        assert_eq!(tagged_322, 28, "expected 28 rows tagged version 3.2.2");
        assert_eq!(tagged_3221, 1, "expected 1 row tagged version 3.2.2.1");
    }

    #[test]
    fn row_for_finds_the_exact_lowercase_hash() {
        let sample = &shipped_rows()[0];
        let found = row_for(&sample.md5)
            .expect("the table must parse")
            .expect("the exact stored hash must be found");
        assert_eq!(found.md5, sample.md5);
        assert_eq!(found.volume, sample.volume);
    }

    #[test]
    fn row_for_is_case_insensitive_on_the_input() {
        let sample = &shipped_rows()[0];
        let upper = sample.md5.to_ascii_uppercase();
        assert_ne!(
            upper, sample.md5,
            "the sample row must actually contain a letter for this test to mean anything"
        );
        let found = row_for(&upper)
            .expect("the table must parse")
            .expect("an uppercase-hex lookup must still find the row");
        assert_eq!(found.md5, sample.md5);
    }

    #[test]
    fn a_hash_matching_no_row_returns_ok_none() {
        assert!(row_for("00000000000000000000000000000000")
            .expect("the table must parse")
            .is_none());
    }

    // -- The error path: unreachable through the public API, since the
    // compiled-in JSON always parses, so it is exercised directly against
    // `parse_table` instead. See this module's doc comment on why a broken
    // table must be reported rather than panicking.

    #[test]
    fn a_malformed_table_is_reported_not_panicked() {
        let result = parse_table("not json at all");
        assert!(
            result.is_err(),
            "malformed JSON must be refused, not accepted"
        );
    }

    #[test]
    fn a_table_missing_the_media_field_is_reported() {
        // Valid JSON, wrong shape: no top-level `media` array.
        let result = parse_table(r#"{"$comment": "no media field here"}"#);
        assert!(
            result.is_err(),
            "JSON missing the `media` array must be refused"
        );
    }

    #[test]
    fn well_formed_json_parses_through_the_same_path_the_shipped_table_uses() {
        let json = r#"{"media": [{"md5": "0123456789abcdef0123456789abcdef", "version": "3.2", "volume": "Workbench3_2", "name": "Test Disk", "source": "test", "sequence": null}]}"#;
        let rows = parse_table(json).expect("well-formed JSON must parse");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].volume, "Workbench3_2");
    }

    // -- The outside check: this table against real media (§4.2 of the
    // design). Sibling of `scripts/media-table-check.py`, and the Rust half
    // of the pattern `core/amigaicon`'s
    // `round_trip_every_icon_in_a_folder_when_asked` established: the same
    // lookup, exercised through `core`'s own public API rather than the
    // Python script's independent re-implementation, so a mistake shared
    // between this module's reader and the shipped JSON cannot hide behind
    // agreement with itself. Needs media ART must never ship, so it is
    // `#[ignore]`d and reads its directory from `ART_MEDIA_DIR` rather than
    // a fixture — never in CI, same reason `ART_ICON_DIR`'s test is not.

    /// Every `.adf`/`.iso`/`.lha` file under `dir`, recursively — the same
    /// extensions `scripts/media-table-check.py` looks for. Read-only:
    /// `std::fs::read_dir` only lists entries.
    fn collect_media_files(dir: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_media_files(&path, out);
            } else if path.extension().is_some_and(|ext| {
                let ext = ext.to_ascii_lowercase();
                ext == "adf" || ext == "iso" || ext == "lha"
            }) {
                out.push(path);
            }
        }
    }

    /// The standing measurement (2026-09-06), against the owner's own
    /// `E:\amiga\Amigatolon\paketler\3.2\AmigaOs 3.2\ADF`: 35 files, all 35
    /// hashing to a row in the shipped table, to the right `name` and the
    /// right `source` (`Hyperion (3.2 base)`), 151 of the table's 186 rows
    /// left unverified (rows the owner does not happen to own a copy of —
    /// expected, and never a failure) and 0 conflicting.
    ///
    /// Three outcomes, kept distinct per this project's own named failure
    /// class (a confident wrong sentence): **verified** (a file here hashes
    /// to this row, via [`row_for`] — the exact function
    /// `commands/`-layer code would call), **unverified** (no file here
    /// does — reported, never asserted, since it says nothing about
    /// whether the row is right), and **conflicting** (a real defect: the
    /// same file's hash resolves to more than one row, which can only
    /// happen if the shipped table itself carries a duplicate `md5` —
    /// something `every_md5_in_the_table_is_distinct` above already
    /// asserts never happens, checked again here independently, against
    /// [`rows`] rather than trusted from that other test). Only
    /// `conflicting` fails this test; `unverified` is printed and left
    /// alone.
    #[test]
    #[ignore = "needs a folder of the owner's own real install media"]
    fn every_real_disk_in_a_folder_is_looked_up_through_cores_own_code_when_asked() {
        let Ok(folder) = std::env::var("ART_MEDIA_DIR") else {
            return;
        };
        let mut entries = Vec::new();
        collect_media_files(std::path::Path::new(&folder), &mut entries);
        entries.sort();

        let table = shipped_rows();

        // Independent of any real file: does the shipped table itself ever
        // claim one hash for two different rows? `row_for` can only ever
        // return one match per hash, so this is the only way "one file
        // matching two rows" could actually happen — checked here against
        // the table directly, not inferred from a lookup result.
        let mut by_md5: std::collections::HashMap<&str, Vec<&MediaRow>> =
            std::collections::HashMap::new();
        for row in table {
            by_md5.entry(row.md5.as_str()).or_default().push(row);
        }
        let mut conflicting: Vec<String> = Vec::new();
        for (md5, rows_for_hash) in &by_md5 {
            if rows_for_hash.len() > 1 {
                let names: Vec<&str> = rows_for_hash.iter().map(|r| r.name.as_str()).collect();
                conflicting.push(format!(
                    "{md5} is claimed by {} rows: {}",
                    rows_for_hash.len(),
                    names.join(", ")
                ));
            }
        }

        let mut checked = 0usize;
        let mut not_in_table = 0usize;
        let mut matched_md5: std::collections::HashSet<String> = std::collections::HashSet::new();
        for entry in &entries {
            let hash = match crate::core::hashing::md5_file(entry) {
                Ok(h) => h,
                Err(err) => {
                    println!("ART_MEDIA_UNREADABLE {}: {err}", entry.display());
                    continue;
                }
            };
            checked += 1;
            match row_for(&hash) {
                Ok(Some(row)) => {
                    matched_md5.insert(row.md5.clone());
                    println!(
                        "ART_MEDIA_MATCH {}: {} ({}, {})",
                        entry.display(),
                        row.name,
                        row.version,
                        row.source
                    );
                }
                Ok(None) => {
                    // No row claims this file. Says nothing about the
                    // file's identity (§4.3 of the design) — reported, not
                    // a failure.
                    not_in_table += 1;
                }
                Err(err) => {
                    conflicting.push(format!("row_for({hash}) for {}: {err}", entry.display()));
                }
            }
        }

        let verified = table
            .iter()
            .filter(|r| matched_md5.contains(&r.md5))
            .count();
        let unverified = table.len() - verified;

        println!(
            "ART_MEDIA_RESULT checked={checked} not_in_table={not_in_table} verified={verified} unverified={unverified} conflicting={}",
            conflicting.len()
        );
        for c in &conflicting {
            println!("ART_MEDIA_CONFLICT {c}");
        }

        assert!(
            conflicting.is_empty(),
            "{} conflicting row(s) — see ART_MEDIA_CONFLICT lines above",
            conflicting.len()
        );
    }

    #[test]
    fn a_parse_failure_is_cached_not_reparsed_on_the_second_call() {
        // Exercises `cached` directly against a private `OnceLock`, so this
        // never touches the process-wide table every other caller shares
        // (the shipped JSON always parses, so that one never holds an error
        // in this test binary).
        //
        // The second call passes *different* malformed JSON than the first.
        // If the caching arrangement in `table()` were broken — reparsing on
        // every call instead of serving the cached result — the second call
        // would parse the second string on its own and very likely report a
        // different `serde_json` error (different text, different byte
        // offset). Getting the *first* call's exact error back on the
        // second call is only possible if the cache, not a fresh parse,
        // answered it — which is the specific guarantee this arrangement
        // exists to give `row_for`/`rows` callers.
        static CACHE: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
        let first = cached(&CACHE, "not json at all").unwrap_err();
        let second = cached(
            &CACHE,
            "{{{ this is a completely different malformed document",
        )
        .unwrap_err();
        assert_eq!(
            format!("{first}"),
            format!("{second}"),
            "the second call must return the first call's cached error, not a fresh parse \
             of the second (different) input"
        );
    }
}
