//! The install-media hash table: a compiled-in list of known AmigaOS install
//! disks, keyed by content hash, and a lookup that respects the shape of the
//! data rather than the shape a naive reader would assume.
//!
//! `media_hashes.json` is adopted from
//! [`rootrootde/emu68hatcher`](https://github.com/rootrootde/emu68hatcher)
//! (MIT) — 186 rows, fetched 2026-09-06 and **not regenerated by this
//! module**. The file's own `$comment` field carries the same provenance and
//! the same two traps this doc repeats, so a reader who opens the JSON
//! directly is warned too:
//!
//! - **The mapping is hash → disk, and it is many-to-one.** One logical disk
//!   has many dumps — `Workbench3_1` alone carries 11 distinct hashes. A
//!   structure keyed *disk → hash* would be wrong; this module never builds
//!   one. `rows()` is a flat list and `row_for()` looks a single hash up in
//!   it — nothing here assumes a disk owns exactly one hash, or the reverse.
//! - **`version` and `source` are reported as the row states them, never
//!   re-derived.** The `Hyperion (3.2.2.1 Hotfix Pack)` source contributes 29
//!   rows: 28 tagged `version: "3.2.2"` and one tagged `"3.2.2.1"`. That is
//!   the source's own disagreement, not this table's mistake and not this
//!   module's to resolve — `row_for` and `rows` hand both fields back exactly
//!   as stored, and nothing here normalises, corrects or collapses them.
//!
//! This table only answers "which row does this hash match" — it makes no
//! claim about the disk. §4.3 of the design (`docs/superpowers/specs/
//! 2026-09-06-media-identification-by-hash-design.md`) is what governs how a
//! caller may phrase a match; this module just hands back the row's fields.
//!
//! ## Loading, and what happens if the shipped JSON is broken
//!
//! Same shape as `core/distro`'s registry: a JSON file in this directory,
//! `include_str!`-ed in, parsed with `serde_json`. Unlike `core/distro`,
//! [`rows`] and [`row_for`] cannot return a [`CoreError`](crate::core::error::CoreError) —
//! their signatures are fixed by later tasks that consume them as plain data
//! (`&'static [MediaRow]`, `Option<&'static MediaRow>`), not a `Result`. So
//! the table is parsed once, lazily, behind a [`std::sync::OnceLock`], and if
//! the compiled-in JSON does not parse, the first call **panics** with a
//! message naming the JSON error.
//!
//! That is a deliberate choice, not an oversight: the table ships inside the
//! binary and never changes at runtime, so a malformed table is a mistake
//! made *before* a release — caught by this module's own
//! `the_shipped_table_has_exactly_186_rows` test (and the rest of the
//! invariant suite below) on every `cargo test`, long before it could reach a
//! user. A runtime `CoreResult` would only give every caller of `rows()` an
//! error path to handle for a condition that a green test suite already
//! rules out. Panicking here is the same reasoning `recipe.rs`'s shipped
//! releases document under "Parsed once, not once per row": the parse
//! *result* is cached, so a broken table would fail identically on the first
//! call and the thousandth — it just fails loudly instead of politely, which
//! is correct for a build-time defect rather than a user's.

use serde::Deserialize;
use std::sync::OnceLock;

/// One row of the table: a single dump's hash and what Emu68 Hatcher's data
/// says about it.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct MediaRow {
    /// 32 lowercase hex characters. Table lookup only — never ART's
    /// integrity hash (that stays SHA-256; see `core/hashing.rs`).
    pub md5: String,
    /// As the row states it. **Not re-derived** — see this module's own doc
    /// comment on the Hotfix Pack disagreement.
    pub version: String,
    /// The AmigaDOS volume name this dump carries — the same value
    /// `core/osinstall/scan.rs` already reads off a real disk's root block.
    pub volume: String,
    /// A human-readable label for the disk, as Hatcher's table names it.
    pub name: String,
    /// Where Hatcher's table says this dump came from. As stated — never
    /// re-derived.
    pub source: String,
    /// The disk's position within its set, when the source states one.
    pub sequence: Option<u32>,
}

/// The shape of the shipped JSON file. `$comment` and `adopted_from` are
/// provenance for a human reader and are not modelled here — an unknown
/// field in the source JSON is simply ignored, not rejected.
#[derive(Debug, Deserialize)]
struct MediaTable {
    media: Vec<MediaRow>,
}

/// The registry as it ships, compiled into the binary.
const MEDIA_HASHES_JSON: &str = include_str!("media_hashes.json");

/// Parsed once, on first use. See this module's doc comment for why a parse
/// failure here panics rather than returning a `Result`.
fn table() -> &'static [MediaRow] {
    static TABLE: OnceLock<Vec<MediaRow>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let parsed: MediaTable = serde_json::from_str(MEDIA_HASHES_JSON).unwrap_or_else(|e| {
            panic!(
                "the shipped install-media hash table does not parse; this is a build-time \
                 defect, not a user's problem: {e}"
            )
        });
        parsed.media
    })
}

/// Every row in the shipped table, in file order. Many rows can share a
/// `volume` — see this module's doc comment on the many-to-one mapping.
pub fn rows() -> &'static [MediaRow] {
    table()
}

/// The row whose `md5` matches `md5`, if any.
///
/// Case-insensitive on the **input** — a user's own hashing tool may emit
/// uppercase hex — but exact on the **stored** value, which the shipped table
/// already carries as lowercase (asserted by this module's own invariant
/// tests). A hash matching no row returns `None`; per §4.3 of the design,
/// that says nothing about the disk's identity and must never be read as a
/// negative claim.
pub fn row_for(md5: &str) -> Option<&'static MediaRow> {
    let needle = md5.to_ascii_lowercase();
    table().iter().find(|row| row.md5 == needle)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn the_shipped_table_has_exactly_186_rows() {
        assert_eq!(rows().len(), 186, "expected 186 rows in the shipped table");
    }

    #[test]
    fn every_md5_in_the_table_is_distinct() {
        let hashes: HashSet<&str> = rows().iter().map(|row| row.md5.as_str()).collect();
        assert_eq!(
            hashes.len(),
            186,
            "expected 186 distinct md5 values, found {}",
            hashes.len()
        );
    }

    #[test]
    fn every_md5_is_32_lowercase_hex_characters() {
        for row in rows() {
            assert_eq!(row.md5.len(), 32, "'{}' is not 32 characters long", row.md5);
            assert!(
                row.md5
                    .chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "'{}' is not lowercase hex",
                row.md5
            );
        }
    }

    #[test]
    fn every_row_has_its_descriptive_fields_filled_in() {
        for row in rows() {
            assert!(!row.version.is_empty(), "{}: empty version", row.md5);
            assert!(!row.volume.is_empty(), "{}: empty volume", row.md5);
            assert!(!row.name.is_empty(), "{}: empty name", row.md5);
            assert!(!row.source.is_empty(), "{}: empty source", row.md5);
        }
    }

    #[test]
    fn the_many_to_one_mapping_is_real_not_assumed() {
        // Named per the design's §2.2 measurement, not the brief's guess: a
        // hash → disk table only means something if more than one hash can
        // point at the same disk, and this asserts the actual counts rather
        // than trusting the doc comment above.
        let count_volume = |volume: &str| rows().iter().filter(|r| r.volume == volume).count();
        assert_eq!(count_volume("Workbench3_1"), 11);
        assert_eq!(count_volume("Install3_1"), 11);
        assert_eq!(count_volume("Locale3_1"), 10);
        assert_eq!(count_volume("Storage3_1"), 10);
        assert_eq!(count_volume("Extras3_1"), 9);
        assert_eq!(count_volume("Fonts3_1"), 6);
    }

    #[test]
    fn the_hotfix_pack_disagreement_is_pinned_not_tidied() {
        let hotfix: Vec<&MediaRow> = rows()
            .iter()
            .filter(|r| r.source == "Hyperion (3.2.2.1 Hotfix Pack)")
            .collect();
        assert_eq!(hotfix.len(), 29, "expected 29 Hotfix Pack rows");

        let tagged_322 = hotfix.iter().filter(|r| r.version == "3.2.2").count();
        let tagged_3221 = hotfix.iter().filter(|r| r.version == "3.2.2.1").count();
        assert_eq!(tagged_322, 28, "expected 28 rows tagged version 3.2.2");
        assert_eq!(tagged_3221, 1, "expected 1 row tagged version 3.2.2.1");
    }

    #[test]
    fn row_for_finds_the_exact_lowercase_hash() {
        let sample = &rows()[0];
        let found = row_for(&sample.md5).expect("the exact stored hash must be found");
        assert_eq!(found.md5, sample.md5);
        assert_eq!(found.volume, sample.volume);
    }

    #[test]
    fn row_for_is_case_insensitive_on_the_input() {
        let sample = &rows()[0];
        let upper = sample.md5.to_ascii_uppercase();
        assert_ne!(
            upper, sample.md5,
            "the sample row must actually contain a letter for this test to mean anything"
        );
        let found = row_for(&upper).expect("an uppercase-hex lookup must still find the row");
        assert_eq!(found.md5, sample.md5);
    }

    #[test]
    fn a_hash_matching_no_row_returns_none() {
        assert!(row_for("00000000000000000000000000000000").is_none());
    }
}
