//! The install-media hash table: a compiled-in list of known AmigaOS install
//! disks, keyed by content hash, and a lookup that respects the shape of the
//! data rather than the shape a naive reader would assume.
//!
//! `media_hashes.json` is adopted from
//! [`rootrootde/emu68hatcher`](https://github.com/rootrootde/emu68hatcher)
//! (MIT) — 186 rows, fetched 2026-09-06 and **not regenerated by this
//! module**. The file's own `$comment` field carries the same provenance and
//! the same two traps this doc repeats, so a reader who opens the JSON
//! directly is warned too:
//!
//! - **The mapping is hash → disk, and it is many-to-one.** One logical disk
//!   has many dumps — `Workbench3_1` alone carries 11 distinct hashes. A
//!   structure keyed *disk → hash* would be wrong; this module never builds
//!   one. `rows()` is a flat list and `row_for()` looks a single hash up in
//!   it — nothing here assumes a disk owns exactly one hash, or the reverse.
//! - **`version` and `source` are reported as the row states them, never
//!   re-derived.** The `Hyperion (3.2.2.1 Hotfix Pack)` source contributes 29
//!   rows: 28 tagged `version: "3.2.2"` and one tagged `"3.2.2.1"`. That is
//!   the source's own disagreement, not this table's mistake and not this
//!   module's to resolve — `row_for` and `rows` hand both fields back exactly
//!   as stored, and nothing here normalises, corrects or collapses them.
//!
//! This table only answers "which row does this hash match" — it makes no
//! claim about the disk. §4.3 of the design (`docs/superpowers/specs/
//! 2026-09-06-media-identification-by-hash-design.md`) is what governs how a
//! caller may phrase a match; this module just hands back the row's fields.
//!
//! ## A second table, ART's own
//!
//! `media_hashes_own.json` (§2/§3.6 of `docs/superpowers/specs/
//! 2026-09-08-os-builder-intake-design.md`) carries what Hatcher's table
//! carries none of: the AmigaOS 3.9 CD-ROM and its update archives. It is a
//! **separate file**, not a merge into `media_hashes.json` — the same rule
//! that keeps `media_hashes_confirmed.json` apart from the table it confirms,
//! applied one level up: the adopted table stays exactly as adopted, and
//! [`MediaRow::table_origin`] is how a caller tells which file answered.
//! [`rows`] serves both files, adopted rows first; [`row_for`] looks in both.
//! Unlike Hatcher's rows, an own-table row can carry a [`MediaRow::kind`], an
//! [`MediaRow::artefact`] slot id and a list of [`MediaRow::filenames`] —
//! fields an adopted row simply defaults, because Hatcher's data never
//! declared them and this module does not invent claims on its behalf.
//!
//! ## Two halves
//!
//! Everything down to [`confirmation_for`] is that pure lookup and depends on
//! nothing but the two compiled-in JSON files — Hatcher's table, and ART's own
//! record of which of its rows a real disk here has actually been hashed
//! against (`media_hashes_confirmed.json`, and the block above
//! [`Confirmation`] is why that is a separate file rather than a column).
//! Below them is [`identify_media_in`], which meets
//! real files: it walks a folder the user named, hashes what it has not
//! already hashed (the result is kept in `super::scan_cache`, against the
//! `(path, size, mtime)` identity that module already keys on — one cache,
//! not a second one), and pairs each file's row with the volume name the
//! disk itself carries. That half necessarily reaches its two sibling
//! modules, `scan` and `scan_cache`; the table half still reaches nothing.
//!
//! ## Loading, and what happens if the shipped JSON is broken
//!
//! Same shape as `core/distro`'s registry: a JSON file in this directory,
//! `include_str!`-ed in, parsed with `serde_json`.
//!
//! [`rows`] and [`row_for`] originally returned plain data —
//! `&'static [MediaRow]` and `Option<&'static MediaRow>` — with no error arm,
//! on the reasoning that the table ships inside the binary, never changes at
//! runtime, and is already guarded by this module's own invariant tests
//! (`the_shipped_adopted_table_has_exactly_186_rows` and the rest below), so a parse
//! failure could only be a defect caught long before a release reached a
//! user. On that reasoning, a broken table simply **panicked** the first
//! time either function ran.
//!
//! **That reasoning was wrong, for the same reason `recipe.rs` documents
//! under "It returns an error and does not panic (fix round 1, F10)".**
//! `panic = "abort"` in the release profile means a panic here does not stay
//! contained to one caller — it takes the whole application down. Shipped
//! data being wrong is still a bug; it should be one that produces a
//! refusal a user can read and a process that is still running, not a crash.
//! So both functions now return [`CoreResult`](crate::core::error::CoreResult),
//! matching `core/distro::profiles()`, which returns a `Result` for exactly
//! this reason.
//!
//! The table is still parsed once, lazily, behind a [`std::sync::OnceLock`]
//! — but what is cached is the parse **result**, not only the success, so a
//! broken table is reported identically on the first call and the
//! thousandth. This is the same arrangement `recipe.rs`'s
//! `shipped_component_overrides` documents under "Parsed once, not once per
//! row": `CoreError` is not `Clone`, so the cache holds the failure as its
//! own text and rebuilds a [`CoreError::Malformed`](crate::core::error::CoreError::Malformed)
//! from it on every subsequent call, with the original error's text
//! unchanged.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

use crate::core::error::{CoreError, CoreResult};
use crate::core::hashing::md5_file;
use crate::core::jobs::{cancelled_error, ProgressSink};

use super::scan;
use super::scan_cache::ScanCache;

/// One row of the table: a single dump's hash and what Emu68 Hatcher's data
/// says about it.
///
/// `Serialize` as well as `Deserialize` because a row crosses the wire whole,
/// inside a [`MediaMatch`]: the screen's sentence names the row's own
/// `name`/`version`/`source` and attributes the claim to Hatcher's table, so
/// every field has to arrive intact rather than being summarised into a
/// string on this side.
/// What kind of medium a row's bytes are. Adopted rows never state one —
/// Hatcher's data has no such field — so they default to `Floppy`, which is
/// what every one of the 186 shipped rows actually is; an own-table row
/// always states its real kind explicitly (`kind` is a required key in
/// `media_hashes_own.json`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum MediaKindTag {
    #[default]
    Floppy,
    Disc,
    Archive,
}

/// Which of the two compiled-in files answered — the fact
/// [`MediaRow::table_origin`] carries, so a caller can attribute a match's
/// provenance sentence correctly. Never read from either file: `media_hashes
/// .json` and `media_hashes_own.json` do not state this about their own
/// rows, so it is stamped on after parsing (see [`parse_own_table`]),
/// `#[serde(skip_deserializing)]` on the field itself, and `Adopted` as the
/// type's `Default` is what makes plain [`parse_table`] — used directly by
/// this module's own error-path tests with hand-written JSON that has no
/// opinion on provenance — produce the right tag without having to say so.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Origin {
    #[default]
    Adopted,
    Own,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaRow {
    /// 32 lowercase hex characters. Table lookup only — never ART's
    /// integrity hash (that stays SHA-256; see `core/hashing.rs`).
    pub md5: String,
    /// As the row states it. **Not re-derived** — see this module's own doc
    /// comment on the Hotfix Pack disagreement.
    pub version: String,
    /// Hatcher's own identifier for the disk this dump is of — **not the
    /// AmigaDOS volume name**, and never to be compared with one.
    ///
    /// This doc comment used to say it was "the same value
    /// `core/osinstall/scan.rs` already reads off a real disk's root block".
    /// **It is not.** Measured 2026-09-06 against the owner's own AmigaOS 3.2
    /// media: **0 of 12 matched.** This field says `Backdrops3_2`,
    /// `LocaleDE3_2`, `DiskDoctor3_2`; the same disks' own root blocks say
    /// `Backdrops3.2`, `Locale-DE`, `DiskDoctor`. Two namespaces — one
    /// somebody else's internal identifier, one what AmigaDOS actually
    /// wrote. Joining them would have reported all 35 of the owner's good
    /// disks as being in conflict with the table.
    ///
    /// So a [`MediaMatch`] carries this field and the disk's own
    /// `volume_name` as two separate facts from two separate sources, and
    /// nothing anywhere compares them or presents this one as the disk's
    /// name.
    pub volume: String,
    /// A human-readable label for the disk, as Hatcher's table names it.
    pub name: String,
    /// Where Hatcher's table says this dump came from. As stated — never
    /// re-derived.
    pub source: String,
    /// The disk's position within its set, when the source states one.
    pub sequence: Option<u32>,
    /// What kind of medium this is. `#[serde(default)]`: Hatcher's rows
    /// never state one and default to [`MediaKindTag::Floppy`], which is
    /// what all 186 of them are; every own-table row states its own.
    #[serde(default)]
    pub kind: MediaKindTag,
    /// The shipped package/recipe id this row's bytes are the media of, when
    /// ART has one — `boingbag-39-1`, `amigaos-39-cd`. `None` for every
    /// adopted row: Hatcher's data names no ART id, and inventing one on its
    /// behalf would be a claim this module does not get to make. `#[serde
    /// (default)]` is belt-and-braces here — `Option<T>` already deserializes
    /// a missing key as `None` — kept for the same reason [`filenames`]
    /// states it explicitly: a reader of this struct should not have to know
    /// which optional fields need the attribute and which do not.
    ///
    /// [`filenames`]: MediaRow::filenames
    #[serde(default)]
    pub artefact: Option<String>,
    /// Names ART has actually seen this artefact ship under —
    /// `["AmigaOS39.iso", "amigaos3.9.iso"]` for the 3.9 CD. A hint for a
    /// drop-folder guide, never a requirement: a file can be renamed and
    /// still hash to this row. Empty for every adopted row.
    #[serde(default)]
    pub filenames: Vec<String>,
    /// Which of the two compiled-in files this row came from. Stamped on
    /// after parsing, never read from either file — see [`Origin`]'s own doc
    /// comment for why the field is `#[serde(skip_deserializing)]` rather
    /// than an ordinary key.
    #[serde(skip_deserializing, default)]
    pub table_origin: Origin,
}

/// The shape of the shipped JSON file. `$comment` and `adopted_from` are
/// provenance for a human reader and are not modelled here — an unknown
/// field in the source JSON is simply ignored, not rejected.
#[derive(Debug, Deserialize)]
struct MediaTable {
    media: Vec<MediaRow>,
}

/// The registry as it ships, compiled into the binary.
const MEDIA_HASHES_JSON: &str = include_str!("media_hashes.json");

/// The shape of ART's own table. `rows`, not `media` — a different key on
/// purpose, so a reader who opens the file cannot mistake it for a copy of
/// the adopted one. `$comment` is provenance for a human reader and is not
/// modelled, same as [`MediaTable`].
#[derive(Debug, Deserialize)]
struct OwnMediaTable {
    rows: Vec<MediaRow>,
}

/// ART's own table, compiled into the binary — see this module's doc comment
/// on the second half of "A second table, ART's own".
const MEDIA_HASHES_OWN_JSON: &str = include_str!("media_hashes_own.json");

/// Parses a media table from its JSON text. Split out of [`cached`] so the
/// failure path — otherwise unreachable through the public API, since the
/// compiled-in JSON always parses — has something to call directly with
/// malformed input.
fn parse_table(json: &str) -> Result<Vec<MediaRow>, String> {
    let parsed: MediaTable = serde_json::from_str(json).map_err(|e| e.to_string())?;
    Ok(parsed.media)
}

/// Parses ART's own table from its JSON text, and stamps every row
/// [`Origin::Own`] — the one fact neither file states about itself. Split out
/// of [`cached`] for the same reason [`parse_table`] is.
fn parse_own_table(json: &str) -> Result<Vec<MediaRow>, String> {
    let parsed: OwnMediaTable = serde_json::from_str(json).map_err(|e| e.to_string())?;
    let mut rows = parsed.rows;
    for row in &mut rows {
        row.table_origin = Origin::Own;
    }
    Ok(rows)
}

/// Both tables, concatenated adopted-first. The `&str` argument is ignored —
/// this combines the **two** compiled-in constants directly rather than
/// parsing whatever text it is handed — so it can still be passed through
/// [`cached`], which every other parse in this module already goes through
/// and which is what makes a broken file panic nobody instead of the whole
/// application (see this module's own doc comment on why `rows`/`row_for`
/// return a `Result` at all).
fn parse_combined(_ignored: &str) -> Result<Vec<MediaRow>, String> {
    let mut combined = parse_table(MEDIA_HASHES_JSON)?;
    combined.extend(parse_own_table(MEDIA_HASHES_OWN_JSON)?);
    Ok(combined)
}

/// Parses `json` into `cache` on first use and hands back a reference into
/// whatever is already there on every call after. What is cached is the
/// parse **result**, not only the success, so a broken file is reported
/// identically on the first call and the thousandth — see this module's doc
/// comment. Split out of [`table`] so a test can hand it a private
/// `OnceLock` and malformed JSON without touching the process-wide table
/// that every other caller shares.
///
/// Generic over what is being parsed because this module now compiles in
/// **two** JSON files — Hatcher's table and ART's own record of which of its
/// rows have been checked against a real disk. Two copies of this
/// arrangement, one per file, is the ART-249 shape: one gets a fix and the
/// other quietly does not.
fn cached<'a, T>(
    cache: &'a OnceLock<Result<T, String>>,
    json: &str,
    format: &'static str,
    parse: fn(&str) -> Result<T, String>,
) -> CoreResult<&'a T> {
    match cache.get_or_init(|| parse(json)) {
        Ok(parsed) => Ok(parsed),
        Err(detail) => Err(CoreError::Malformed {
            format: format.into(),
            detail: detail.clone(),
        }),
    }
}

/// The adopted table alone, parsed once on first use. Kept as its own
/// function — rather than filtering [`rows`] — so this module's own tests
/// can pin the adopted table's invariants (186 rows and counting) without
/// them drifting the moment ART's own table grows a row.
fn table() -> CoreResult<&'static [MediaRow]> {
    static TABLE: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
    Ok(cached(
        &TABLE,
        MEDIA_HASHES_JSON,
        "install-media hash table",
        parse_table,
    )?
    .as_slice())
}

/// ART's own table alone, parsed once on first use — the [`table`] counterpart
/// for `media_hashes_own.json`.
fn own_table() -> CoreResult<&'static [MediaRow]> {
    static OWN_TABLE: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
    Ok(cached(
        &OWN_TABLE,
        MEDIA_HASHES_OWN_JSON,
        "ART's own install-media hash table",
        parse_own_table,
    )?
    .as_slice())
}

/// Both tables, adopted rows first, parsed once on first use. Its own cache
/// rather than a fresh `Vec` built from [`table`] and [`own_table`] on every
/// call, because [`rows`] promises a `&'static [MediaRow]` — a slice into
/// memory that outlives the call — and a freshly allocated `Vec` cannot back
/// one without leaking.
fn combined_table() -> CoreResult<&'static [MediaRow]> {
    static COMBINED: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
    Ok(cached(&COMBINED, "", "install-media hash table", parse_combined)?.as_slice())
}

/// Every row in both shipped tables, adopted rows first, each in its own
/// file order. Many rows can share a `volume` — see this module's doc
/// comment on the many-to-one mapping. Check [`MediaRow::table_origin`] to
/// tell which file a given row came from.
pub fn rows() -> CoreResult<&'static [MediaRow]> {
    combined_table()
}

/// The row whose `md5` matches `md5`, if any — in either table.
///
/// Case-insensitive on the **input** — a user's own hashing tool may emit
/// uppercase hex — but exact on the **stored** value, which both shipped
/// tables already carry as lowercase (asserted by this module's own
/// invariant tests). A hash matching no row returns `Ok(None)`; per §4.3 of
/// the design, that says nothing about the disk's identity and must never be
/// read as a negative claim. `Err` means a table itself could not be read,
/// which is a different situation entirely and must never be collapsed into
/// "no match".
pub fn row_for(md5: &str) -> CoreResult<Option<&'static MediaRow>> {
    let needle = md5.to_ascii_lowercase();
    Ok(rows()?.iter().find(|row| row.md5 == needle))
}

// ---------------------------------------------------------------------------
// Which rows have actually been checked against a real disk — ART's own record
// ---------------------------------------------------------------------------
//
// §4.3 of the design: *"Where the owner's own media has confirmed a row, ART
// may say so and name what confirmed it. Where it has not, ART says the row is
// unconfirmed. Two different sentences, never collapsed."*
//
// A screen cannot say that from the table alone. The table is Hatcher's, and
// every row in it looks exactly as authoritative as every other row; on
// 2026-09-06 **35 of the 186 rows had been hashed off a real disk here and
// 151 had not.** Presenting the 151 with the same confidence as the 35 is the
// defect this project pays most for — a confident sentence with nothing behind
// it — and presenting the 35 with the same reservation as the 151 throws away
// a real check that a person really ran.
//
// So ART ships its own record, in its own file
// (`media_hashes_confirmed.json`), generated by
// `scripts/media-table-check.py --emit-confirmed` from an actual run against
// actual disks. It is deliberately **not** a field added to Hatcher's rows:
// the adopted table stays exactly as adopted, and a reader can tell at a
// glance which claim came from whom. Same rule as `MediaMatch`'s two middle
// fields, one level up.
//
// **A row missing from this file is not suspect.** It means nobody here owns a
// disk that hashes to it, which is true of most of the table and says nothing
// at all about the row.

/// A real check somebody really ran, and what it was run against.
///
/// Both fields are shown to the user verbatim — the sentence a match carries
/// is *"checked against `against`, on `checked`"* — because a confirmation
/// that cannot say what confirmed it is not a citation, only a badge.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Confirmation {
    /// ISO date the check was run.
    pub checked: String,
    /// What it was run against, in the words the screen shows.
    pub against: String,
}

/// The shape of the shipped confirmation file. `$comment` is provenance for a
/// human reader and is not modelled — an unknown field is ignored.
#[derive(Debug, Deserialize)]
struct ConfirmedFile {
    checks: Vec<ConfirmedCheck>,
}

/// One run of the check script: the material, the day, and the hashes a file
/// under it actually produced.
#[derive(Debug, Deserialize)]
struct ConfirmedCheck {
    checked: String,
    against: String,
    md5: Vec<String>,
}

/// ART's own confirmation record as it ships, compiled into the binary.
const MEDIA_HASHES_CONFIRMED_JSON: &str = include_str!("media_hashes_confirmed.json");

/// Flattens the file's runs into one `(md5, confirmation)` list.
///
/// A hash confirmed by more than one run keeps the **first** — the file is
/// small, ordered, and hand-reviewed in a diff, and picking a winner silently
/// would be a conclusion ART drew rather than a fact it read. Split out of
/// [`confirmations`] for the same reason [`parse_table`] is: the failure path
/// is otherwise unreachable, since the compiled-in JSON always parses.
fn parse_confirmed(json: &str) -> Result<Vec<(String, Confirmation)>, String> {
    let parsed: ConfirmedFile = serde_json::from_str(json).map_err(|e| e.to_string())?;
    let mut flattened: Vec<(String, Confirmation)> = Vec::new();
    for check in parsed.checks {
        for md5 in check.md5 {
            let md5 = md5.to_ascii_lowercase();
            if flattened.iter().any(|(seen, _)| *seen == md5) {
                continue;
            }
            flattened.push((
                md5,
                Confirmation {
                    checked: check.checked.clone(),
                    against: check.against.clone(),
                },
            ));
        }
    }
    Ok(flattened)
}

/// Parsed once, on first use.
fn confirmations() -> CoreResult<&'static [(String, Confirmation)]> {
    static CONFIRMED: OnceLock<Result<Vec<(String, Confirmation)>, String>> = OnceLock::new();
    Ok(cached(
        &CONFIRMED,
        MEDIA_HASHES_CONFIRMED_JSON,
        "install-media confirmation record",
        parse_confirmed,
    )?
    .as_slice())
}

/// The check that confirmed the row this hash belongs to, if one has.
///
/// `Ok(None)` is **"nobody here has checked this row against a real disk"** —
/// never "this row is wrong" and never "this file is not what it says". Most
/// of the table answers `None` and that is the expected, uninteresting case.
/// `Err` means ART's own record could not be read, which is a different
/// situation again and must not be collapsed into either.
pub fn confirmation_for(md5: &str) -> CoreResult<Option<&'static Confirmation>> {
    let needle = md5.to_ascii_lowercase();
    Ok(confirmations()?
        .iter()
        .find(|(hash, _)| *hash == needle)
        .map(|(_, confirmation)| confirmation))
}

// ---------------------------------------------------------------------------
// Identifying a folder against the table
// ---------------------------------------------------------------------------
//
// The half of this module that meets real files. Everything above is a pure
// lookup in compiled-in data; everything below walks a folder the user
// named, hashes what is in it, and joins the answer to what the disks
// themselves say.
//
// **Two facts, two sources, never reconciled.** [`MediaMatch::volume_name`]
// is what the disk's own root block says, read by `scan::identify` exactly
// as the OS Builder already reads it. [`MediaMatch::row`] is what the table
// says about the file's bytes. They are kept apart in the type because they
// *are* apart in reality — see [`MediaRow::volume`] for the measurement that
// settled it — and because §4.3 of the design turns on the two being
// reported separately: a hit adds a claim attributed to Hatcher's table, and
// a miss subtracts nothing from what the volume name already established.
//
// **It is an index, not a verdict.** The owner's own phrasing for what this
// is for — *"ne nerede duruyor öğrenir"*, so it learns what is where — and
// it is why the result is cached rather than recomputed: asking again which
// disks are in a folder must not mean reading every byte of them again.
//
// **The name.** There is already a `MediaMatch` in this module tree —
// `scan::MediaMatch`, the enum answering "which file in this folder carries
// this volume name". This one answers "what is this file", which is a
// different question about a different thing, and callers spell it
// `mediahash::MediaMatch` rather than importing it bare.

/// What one file in a media folder turned out to be.
///
/// Four fields, and the two middle ones come from different places on
/// purpose: `volume_name` is the disk's own answer, `row` is the table's.
/// Either can be absent without saying anything about the other — a disk
/// whose root block ART cannot read is still hashable, and a file in no row
/// still has a perfectly good volume name.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaMatch {
    pub path: PathBuf,
    /// What **the disk** says its volume is called, read off its root block
    /// by `scan::identify`. `None` when this file is not something ART can
    /// open as media at all — an `.lha` archive, or a damaged image — which
    /// is not a failure and does not stop it being hashed and looked up.
    ///
    /// **Never compared with [`MediaRow::volume`]** — see that field.
    pub volume_name: Option<String>,
    /// What **the table** says about these bytes, or `None` when no row
    /// claims them.
    ///
    /// `None` is "not in the table", which is a claim about the table and
    /// not about the disk: 151 of the 186 rows are themselves unconfirmed,
    /// and a re-imaged disk is a legitimate miss. It must never be rendered
    /// as "not genuine", and it must never weaken what `volume_name`
    /// already established.
    pub row: Option<MediaRow>,
    /// The key the lookup was made with, 32 lowercase hex characters.
    /// Carried so the screen can show what was asked, and so a user can take
    /// it to Hatcher's own table for a row ART does not ship.
    pub md5: String,
    /// The check that confirmed `row`, when one has — see
    /// [`confirmation_for`].
    ///
    /// `None` alongside a `Some(row)` is **"matched a row nobody here has
    /// checked against a real disk"**, which is a weaker sentence than a
    /// confirmed match and a completely different one from "not in the
    /// table". 151 of the 186 rows answer `None`, so collapsing the two
    /// would give 151 rows a confidence that was never earned.
    ///
    /// Always `None` when `row` is `None`: a confirmation is about a row, and
    /// there is no row here to have been confirmed.
    pub confirmed: Option<Confirmation>,
}

/// What one pass over a media folder found.
///
/// The counts and `unreadable` are here so the four endings §4.3 requires
/// stay distinct — "matched", "not in the table", "could not be read" and
/// "not hashed yet" are four different sentences and four different next
/// steps, and a screen that only received `matches` could not tell the third
/// from the first two.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Identification {
    /// One entry per candidate file that could be hashed, in path order.
    pub matches: Vec<MediaMatch>,
    /// Candidates whose bytes could not be read at all. Reported rather than
    /// dropped: a file silently missing from `matches` would read as a file
    /// that is not there.
    pub unreadable: Vec<PathBuf>,
    /// How many files this pass actually read and hashed.
    pub hashed: usize,
    /// How many were answered out of the scan cache without being read.
    pub remembered: usize,
}

/// The file extensions a media folder is searched for, lowercase.
///
/// The same six `scripts/media-table-check.py` looks at, deliberately: the
/// script and this function must ask the same question of a folder, or the
/// outside check stops checking the thing that ships. `lzh`, `zip` and `7z`
/// joined `adf`/`iso`/`lha` so a re-packed archive — anything
/// `core::osinstall::scan::find_packages` can actually open — is at least
/// reported rather than silently invisible to identification (design's
/// §3.6, 2026-09-08).
const MEDIA_EXTENSIONS: [&str; 6] = ["adf", "iso", "lha", "lzh", "zip", "7z"];

/// Every file in `folder` this module will try to identify, in sorted path
/// order.
///
/// Not recursive, matching `scan::find_media`: the OS Builder's media folder
/// is a folder of disks, and a layered install names its folders separately
/// rather than nesting them. `symlink_metadata`, so a symlink is never
/// followed — `find_media`'s own rule and its reason.
///
/// A folder that cannot be read is an error, not an empty list: the user
/// just named it, so "that path is gone" is the true sentence.
pub fn candidates_in(folder: &Path) -> CoreResult<Vec<PathBuf>> {
    let mut found: Vec<PathBuf> = Vec::new();
    for entry in std::fs::read_dir(folder)? {
        let path = entry?.path();
        let Ok(metadata) = std::fs::symlink_metadata(&path) else {
            continue;
        };
        if !metadata.is_file() {
            continue;
        }
        let is_media = path.extension().is_some_and(|ext| {
            let ext = ext.to_string_lossy().to_ascii_lowercase();
            MEDIA_EXTENSIONS.contains(&ext.as_str())
        });
        if is_media {
            found.push(path);
        }
    }
    found.sort();
    Ok(found)
}

/// Join one file's two facts into a [`MediaMatch`].
///
/// Split out so the join itself can be tested against a hash that really is
/// in the table — which no synthetic fixture can ever produce, since ART
/// ships no copyrighted media and nobody can invent an MD5 preimage.
pub fn match_for(path: &Path, volume_name: Option<String>, md5: String) -> CoreResult<MediaMatch> {
    let row = row_for(&md5)?.cloned();
    // Asked only when there is a row to have been confirmed. A confirmation
    // hanging off a file that matched nothing would be a claim about a disk,
    // which is the one thing this module never makes.
    let confirmed = match row {
        Some(_) => confirmation_for(&md5)?.cloned(),
        None => None,
    };
    Ok(MediaMatch {
        path: path.to_path_buf(),
        volume_name,
        row,
        md5,
        confirmed,
    })
}

/// What the disk itself says it is called, as cheaply as it can be had.
///
/// The cached listing first — a preview that has already walked this medium
/// recorded its volume name, and re-opening a 468 MB disc to read a string
/// ART already has is the exact cost `scan_cache` exists to avoid. Otherwise
/// `scan::identify`, which is the one producer of this answer; nothing here
/// re-implements the probe.
fn volume_name_for(path: &Path, cache: &ScanCache) -> Option<String> {
    if let Some(listing) = cache.lookup(path) {
        return Some(listing.volume_name);
    }
    scan::identify(path).map(|found| found.volume_name)
}

/// What the scan cache **already knows** about the candidates in `folder` —
/// hashing nothing.
///
/// **It may still open a file, and the first version of this sentence claimed
/// otherwise** (fix round 1, F10). No candidate is *hashed*: that is the whole
/// point, and it is what keeps a 490 MB ISO off a command thread. But a file
/// whose md5 the cache holds and whose *listing* it does not goes through
/// [`volume_name_for`], which falls back to `scan::identify` and opens it — a
/// bounded probe of a root block or a volume descriptor, not a read of the
/// file. Said plainly here because this module's rules are enforced by its
/// doc comments, and one that overclaims is a rule nobody can rely on.
///
/// [`identify_media_in`]'s companion, and deliberately not a mode of it. That
/// function is the pass that *does* the work and takes a
/// [`ProgressSink`](crate::core::jobs::ProgressSink) because it is long; this
/// one answers out of what that pass already recorded, so a second screen can
/// join a hash to a slot without a 490 MB ISO being read a second time on a
/// command thread (§54: a long operation belongs on a job, and the job that
/// hashes a media folder already exists — `osinstall_identify_media`).
///
/// **A candidate the cache cannot answer for is simply absent from the
/// result**, and that is a claim about the cache, never about the file: it
/// means "nobody has hashed this yet", not "these bytes are in no row". A
/// caller must therefore never render an absence here as *not in the table* —
/// [`MediaMatch::row`]`: None` is the sentence for that, and it only ever
/// arrives for a file that really was hashed.
///
/// `unreadable` has no counterpart here for the same reason: nothing is read,
/// so nothing can be found unreadable.
pub fn remembered_media_in(folder: &Path, cache: &ScanCache) -> CoreResult<Vec<MediaMatch>> {
    let mut found = Vec::new();
    for path in candidates_in(folder)? {
        let Some(md5) = cache.lookup_md5(&path) else {
            continue;
        };
        found.push(match_for(&path, volume_name_for(&path, cache), md5)?);
    }
    Ok(found)
}

/// Identify every candidate file in `folder`, hashing only what the cache
/// cannot already answer.
///
/// **Long, so it takes a [`ProgressSink`]** (§54/§55). The total is the
/// number of candidate files and is known before the first byte is read, so
/// the bar is a real one — this project's named defect is a fixed-width bar
/// over an unknown total, which looks like progress and carries none.
///
/// **Cancellation is checked between whole files, never mid-read.** The only
/// thing this writes is cache entries, one per completed file, each through
/// `atomic_write`; stopping therefore leaves the files it already did
/// recorded correctly and the ones it did not reach untouched, and never a
/// half-written entry.
///
/// A file whose bytes cannot be read goes into `unreadable` and the pass
/// carries on. One unreadable file in a folder of thirty-five must not cost
/// the other thirty-four, and it must not disappear either.
pub fn identify_media_in(
    folder: &Path,
    cache: &ScanCache,
    progress: &dyn ProgressSink,
) -> CoreResult<Identification> {
    let candidates = candidates_in(folder)?;
    let total = candidates.len() as u64;

    let mut found = Identification {
        matches: Vec::new(),
        unreadable: Vec::new(),
        hashed: 0,
        remembered: 0,
    };

    progress.report(0, Some(total), "");
    for (index, path) in candidates.iter().enumerate() {
        // Between whole files, before this one is opened: the only work
        // already committed is the previous file's cache entry, which is
        // written and fsynced or not written at all.
        if progress.is_cancelled() {
            return Err(cancelled_error());
        }

        let done = index as u64 + 1;
        let name = path
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();

        let md5 = match cache.lookup_md5(path) {
            Some(remembered) => {
                found.remembered += 1;
                remembered
            }
            None => match md5_file(path) {
                Ok(md5) => {
                    cache.store_md5(path, &md5);
                    found.hashed += 1;
                    md5
                }
                Err(_) => {
                    // Reported, never fatal and never silently dropped.
                    found.unreadable.push(path.clone());
                    progress.report(done, Some(total), &name);
                    continue;
                }
            },
        };

        found
            .matches
            .push(match_for(path, volume_name_for(path, cache), md5)?);
        progress.report(done, Some(total), &name);
    }

    Ok(found)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Unwraps [`rows`]'s `CoreResult` — the shipped tables always parse, so
    /// every test above the error-path tests below treats a failure here as
    /// a hard test bug rather than something to assert about. Both tables,
    /// adopted first — see [`adopted_shipped_rows`] and [`own_shipped_rows`]
    /// for the two halves on their own.
    fn shipped_rows() -> &'static [MediaRow] {
        rows().expect("the shipped tables must parse")
    }

    /// The adopted table alone, unwrapped the same way [`shipped_rows`] is.
    /// Kept separate so the adopted table's own pinned invariants (186 rows,
    /// the Hotfix Pack disagreement) never drift just because ART's own
    /// table gained a row — the adopted table stays exactly as adopted.
    fn adopted_shipped_rows() -> &'static [MediaRow] {
        table().expect("the adopted table must parse")
    }

    /// ART's own table alone, unwrapped the same way.
    fn own_shipped_rows() -> &'static [MediaRow] {
        own_table().expect("ART's own table must parse")
    }

    #[test]
    fn the_shipped_adopted_table_has_exactly_186_rows() {
        assert_eq!(
            adopted_shipped_rows().len(),
            186,
            "expected 186 rows in the adopted table"
        );
    }

    #[test]
    fn every_md5_in_the_adopted_table_is_distinct() {
        let hashes: HashSet<&str> = adopted_shipped_rows()
            .iter()
            .map(|row| row.md5.as_str())
            .collect();
        assert_eq!(
            hashes.len(),
            186,
            "expected 186 distinct md5 values, found {}",
            hashes.len()
        );
    }

    // -- ART's own table (§3.6 of `docs/superpowers/specs/
    // 2026-09-08-os-builder-intake-design.md`): the AmigaOS 3.9 CD and its
    // update archives, none of which the adopted table carries.

    #[test]
    fn the_shipped_own_table_has_exactly_8_rows() {
        // Not the design's §2 table's eleven rows plus HstWB's other CD
        // hash: checked against the real adopted table 2026-09-08, four of
        // those twelve candidate hashes turned out to already be adopted
        // rows (Hatcher's own "Haage and Partners (3.9)" AmigaOS 3.9 CD, BB1,
        // BB2 and BB3&4 entries) — caught by
        // `no_md5_is_shared_between_the_adopted_and_own_tables` below, and
        // left out of `media_hashes_own.json` on purpose rather than shipped
        // as a duplicate. Eight hashes are genuinely not in the adopted
        // table.
        assert_eq!(
            own_shipped_rows().len(),
            8,
            "expected 8 rows in ART's own table"
        );
    }

    #[test]
    fn every_md5_in_the_own_table_is_distinct() {
        let hashes: HashSet<&str> = own_shipped_rows()
            .iter()
            .map(|row| row.md5.as_str())
            .collect();
        assert_eq!(
            hashes.len(),
            own_shipped_rows().len(),
            "expected every md5 in ART's own table to be distinct"
        );
    }

    /// The invariant the brief calls out by name: an md5 present in both
    /// tables must fail at this level, as a shipped-data defect — never
    /// resolved silently by whichever table [`row_for`] happens to search
    /// first.
    #[test]
    fn no_md5_is_shared_between_the_adopted_and_own_tables() {
        let adopted: HashSet<&str> = adopted_shipped_rows()
            .iter()
            .map(|row| row.md5.as_str())
            .collect();
        let shared: Vec<&str> = own_shipped_rows()
            .iter()
            .map(|row| row.md5.as_str())
            .filter(|md5| adopted.contains(md5))
            .collect();
        assert!(
            shared.is_empty(),
            "md5(s) claimed by both tables: {shared:?}"
        );
    }

    /// [`rows`] serves both files, adopted rows first — not interleaved, not
    /// own-first — so a caller that only wants "the adopted 186" can still
    /// take a fixed-size prefix if it ever needs to (nothing shipped does
    /// today; this pins the ordering the doc comment promises).
    #[test]
    fn rows_serves_both_tables_adopted_first() {
        let combined = shipped_rows();
        assert_eq!(combined.len(), 186 + 8);
        assert!(
            combined[..186]
                .iter()
                .all(|row| row.table_origin == Origin::Adopted),
            "the first 186 rows must all be adopted"
        );
        assert!(
            combined[186..]
                .iter()
                .all(|row| row.table_origin == Origin::Own),
            "everything after the adopted 186 must be ART's own"
        );
    }

    /// Every adopted row defaults the three fields Hatcher's data never
    /// states, rather than any of them being left to whatever `derive
    /// (Default)` on the enum happens to pick without this being asserted.
    #[test]
    fn adopted_rows_default_kind_artefact_and_filenames() {
        for row in adopted_shipped_rows() {
            assert_eq!(
                row.kind,
                MediaKindTag::Floppy,
                "{}: adopted rows default to floppy",
                row.md5
            );
            assert!(
                row.artefact.is_none(),
                "{}: an adopted row must carry no ART id",
                row.md5
            );
            assert!(
                row.filenames.is_empty(),
                "{}: an adopted row must carry no filenames",
                row.md5
            );
            assert_eq!(row.table_origin, Origin::Adopted);
        }
    }

    /// A real own-table row, pinned end to end: HstWB's other accepted hash
    /// for the AmigaOS 3.9 CD-ROM (design's §2; the owner's own copy hashes
    /// to `3cb96e77…`, which turned out to already be an *adopted* row — see
    /// [`the_shipped_own_table_has_exactly_8_rows`]) resolves through the
    /// same [`row_for`] a caller would use, and carries every slot field the
    /// design specifies.
    #[test]
    fn the_amigaos_39_cd_own_row_carries_its_slot_fields() {
        let row = row_for("e32a107e68edfc9b28a2fe075e32e5f6")
            .expect("the tables must parse")
            .expect("HstWB's other AmigaOS 3.9 CD-ROM hash is in ART's own table");
        assert_eq!(row.kind, MediaKindTag::Disc);
        assert_eq!(row.artefact.as_deref(), Some("amigaos-39-cd"));
        assert_eq!(row.volume, "AmigaOS3.9");
        assert_eq!(row.table_origin, Origin::Own);
        assert!(row.filenames.iter().any(|f| f == "AmigaOS39.iso"));
    }

    /// **The duplicate the invariant test above exists to catch, proven
    /// negative.** The owner's own `AmigaOS39.iso` hashes to `3cb96e77…`,
    /// which is an *adopted* row (Hatcher's own "AmigaOS 3.9", sourced
    /// "Haage and Partners (3.9)") — not one of ART's own, and not tagged
    /// `disc`/`amigaos-39-cd` at all, because adopted rows carry none of
    /// those fields. A caller must not assume every AmigaOS 3.9 hash answers
    /// through ART's own table just because most of them do.
    #[test]
    fn the_owners_cd_hash_resolves_through_the_adopted_table_not_arts_own() {
        let row = row_for("3cb96e77d922a4f8eb696e525a240448")
            .expect("the tables must parse")
            .expect("this hash is a real Hatcher row");
        assert_eq!(row.table_origin, Origin::Adopted);
        assert_eq!(row.source, "Haage and Partners (3.9)");
        assert_eq!(
            row.kind,
            MediaKindTag::Floppy,
            "adopted rows default their kind"
        );
        assert!(row.artefact.is_none(), "adopted rows carry no ART id");
    }

    #[test]
    fn every_md5_is_32_lowercase_hex_characters() {
        for row in shipped_rows() {
            assert_eq!(row.md5.len(), 32, "'{}' is not 32 characters long", row.md5);
            assert!(
                row.md5
                    .chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "'{}' is not lowercase hex",
                row.md5
            );
        }
    }

    #[test]
    fn every_row_has_its_descriptive_fields_filled_in() {
        for row in shipped_rows() {
            assert!(!row.version.is_empty(), "{}: empty version", row.md5);
            assert!(!row.volume.is_empty(), "{}: empty volume", row.md5);
            assert!(!row.name.is_empty(), "{}: empty name", row.md5);
            assert!(!row.source.is_empty(), "{}: empty source", row.md5);
        }
    }

    #[test]
    fn the_many_to_one_mapping_is_real_not_assumed() {
        // Named per the design's §2.2 measurement, not the brief's guess: a
        // hash → disk table only means something if more than one hash can
        // point at the same disk, and this asserts the actual counts rather
        // than trusting the doc comment above.
        let count_volume =
            |volume: &str| shipped_rows().iter().filter(|r| r.volume == volume).count();
        assert_eq!(count_volume("Workbench3_1"), 11);
        assert_eq!(count_volume("Install3_1"), 11);
        assert_eq!(count_volume("Locale3_1"), 10);
        assert_eq!(count_volume("Storage3_1"), 10);
        assert_eq!(count_volume("Extras3_1"), 9);
        assert_eq!(count_volume("Fonts3_1"), 6);
    }

    #[test]
    fn the_hotfix_pack_disagreement_is_pinned_not_tidied() {
        let hotfix: Vec<&MediaRow> = shipped_rows()
            .iter()
            .filter(|r| r.source == "Hyperion (3.2.2.1 Hotfix Pack)")
            .collect();
        assert_eq!(hotfix.len(), 29, "expected 29 Hotfix Pack rows");

        let tagged_322 = hotfix.iter().filter(|r| r.version == "3.2.2").count();
        let tagged_3221 = hotfix.iter().filter(|r| r.version == "3.2.2.1").count();
        assert_eq!(tagged_322, 28, "expected 28 rows tagged version 3.2.2");
        assert_eq!(tagged_3221, 1, "expected 1 row tagged version 3.2.2.1");
    }

    // -- ART's own confirmation record, and the 35/151 split it exists for

    #[test]
    fn every_confirmed_hash_names_a_row_that_is_actually_in_the_table() {
        // The record and the table are two files, generated on two different
        // days by two different processes. A row dropped from Hatcher's table
        // would leave a confirmation pointing at nothing — a check ART claims
        // to have run against a row it no longer ships. Nothing else in the
        // build notices that.
        for (md5, _) in confirmations().expect("the shipped record must parse") {
            assert!(
                row_for(md5).expect("the table must parse").is_some(),
                "{md5} is recorded as confirmed but is in no row of the shipped table"
            );
        }
    }

    #[test]
    fn the_shipped_record_confirms_35_of_the_186_rows_and_not_the_other_151() {
        // The standing measurement, as a number rather than a feeling
        // (`scripts/media-table-check.py`, 2026-09-06: 35 verified, 151
        // unverified, 0 conflicting). Both halves are asserted: a record that
        // confirmed everything would be as wrong as one that confirmed
        // nothing, and only the *pair* says the screen has two sentences to
        // choose between.
        let confirmed = confirmations().expect("the shipped record must parse");
        assert_eq!(confirmed.len(), 35, "expected 35 confirmed rows");
        // Scoped to the *adopted* table on purpose — the 35/151 split is a
        // measurement of `media_hashes.json` specifically (the same file
        // `src/i18n/media-table-counts.test.ts` reads), and ART's own table
        // gaining a row must not silently move this number.
        let unconfirmed = adopted_shipped_rows()
            .iter()
            .filter(|row| {
                confirmation_for(&row.md5)
                    .expect("the record must parse")
                    .is_none()
            })
            .count();
        assert_eq!(
            unconfirmed, 151,
            "expected 151 rows nobody here has checked"
        );
    }

    #[test]
    fn a_confirmation_says_what_confirmed_it_and_when() {
        // A badge with nothing behind it is the failure this record exists to
        // avoid, so the fields the sentence is built from must be present and
        // non-empty for every single entry — not just for the one this test
        // happens to look at.
        for (md5, confirmation) in confirmations().expect("the shipped record must parse") {
            assert!(!confirmation.checked.is_empty(), "{md5}: empty 'checked'");
            assert!(!confirmation.against.is_empty(), "{md5}: empty 'against'");
        }
        // Workbench 3.2's own dump, whose hash the plan states independently
        // of this file (`5edf0b7a…`) — so a record that silently confirmed a
        // different set could not pass this.
        let found = confirmation_for("5edf0b7a10409ef992ea351565ef8b6c")
            .expect("the record must parse")
            .expect("the owner's own Workbench 3.2 disk confirmed this row");
        assert_eq!(found.checked, "2026-09-06");
        assert!(
            found.against.contains("AmigaOS 3.2"),
            "the citation must name the material: {}",
            found.against
        );
    }

    #[test]
    fn a_row_nobody_here_owns_a_disk_for_is_unconfirmed_not_wrong() {
        // An Amiga Technologies 3.1 row: really in the table, and really not
        // something anyone here has hashed off a disk. `None` here is the
        // *unconfirmed* sentence, which is neither "not in the table" (the
        // row is right there) nor a defect.
        let row = shipped_rows()
            .iter()
            .find(|r| r.source == "Escom")
            .expect("the shipped table carries Escom rows");
        assert!(
            row_for(&row.md5).expect("the table must parse").is_some(),
            "the row itself must be present — otherwise this tests the wrong thing"
        );
        assert!(
            confirmation_for(&row.md5)
                .expect("the record must parse")
                .is_none(),
            "{} is not something anyone here has a disk for",
            row.name
        );
    }

    #[test]
    fn confirmation_for_is_case_insensitive_on_the_input_like_row_for() {
        let (md5, _) = &confirmations().expect("the shipped record must parse")[0];
        let upper = md5.to_ascii_uppercase();
        assert_ne!(&upper, md5, "the sample must contain a letter");
        assert!(confirmation_for(&upper)
            .expect("the record must parse")
            .is_some());
    }

    #[test]
    fn a_malformed_confirmation_record_is_reported_not_panicked() {
        assert!(
            parse_confirmed("not json at all").is_err(),
            "malformed JSON must be refused, not accepted"
        );
    }

    /// `scripts/media-table-check.py --emit-confirmed` now appends a check
    /// rather than replacing the file (M4, fix wave 2), so two runs against
    /// two different bodies of media can both name the same hash — the
    /// owner's 3.2 disks re-verified on a later day, say. `parse_confirmed`
    /// keeps the **first** run's `Confirmation` for a repeated hash, which is
    /// this test: earlier provenance for a hash must survive a later run that
    /// happens to re-confirm it, and the later run's *other*, genuinely new
    /// hash must still come through.
    #[test]
    fn two_checks_naming_the_same_hash_keep_the_first_runs_confirmation() {
        let json = r#"{
            "checks": [
                {"checked": "2026-01-01", "against": "first run", "md5": ["aaaa"]},
                {"checked": "2026-06-01", "against": "second run", "md5": ["AAAA", "bbbb"]}
            ]
        }"#;
        let flattened = parse_confirmed(json).expect("must parse");
        assert_eq!(
            flattened.len(),
            2,
            "one entry per distinct hash, not per check"
        );

        let (_, first_hash) = flattened
            .iter()
            .find(|(md5, _)| md5 == "aaaa")
            .expect("the repeated hash must still be present");
        assert_eq!(
            first_hash.against, "first run",
            "the earlier check's provenance must win over the later, repeating one"
        );

        let (_, second_hash) = flattened
            .iter()
            .find(|(md5, _)| md5 == "bbbb")
            .expect("the second run's own, non-repeated hash must still be recorded");
        assert_eq!(second_hash.against, "second run");
    }

    #[test]
    fn row_for_finds_the_exact_lowercase_hash() {
        let sample = &shipped_rows()[0];
        let found = row_for(&sample.md5)
            .expect("the table must parse")
            .expect("the exact stored hash must be found");
        assert_eq!(found.md5, sample.md5);
        assert_eq!(found.volume, sample.volume);
    }

    #[test]
    fn row_for_is_case_insensitive_on_the_input() {
        let sample = &shipped_rows()[0];
        let upper = sample.md5.to_ascii_uppercase();
        assert_ne!(
            upper, sample.md5,
            "the sample row must actually contain a letter for this test to mean anything"
        );
        let found = row_for(&upper)
            .expect("the table must parse")
            .expect("an uppercase-hex lookup must still find the row");
        assert_eq!(found.md5, sample.md5);
    }

    #[test]
    fn a_hash_matching_no_row_returns_ok_none() {
        assert!(row_for("00000000000000000000000000000000")
            .expect("the table must parse")
            .is_none());
    }

    // -- The error path: unreachable through the public API, since the
    // compiled-in JSON always parses, so it is exercised directly against
    // `parse_table` instead. See this module's doc comment on why a broken
    // table must be reported rather than panicking.

    #[test]
    fn a_malformed_table_is_reported_not_panicked() {
        let result = parse_table("not json at all");
        assert!(
            result.is_err(),
            "malformed JSON must be refused, not accepted"
        );
    }

    #[test]
    fn a_table_missing_the_media_field_is_reported() {
        // Valid JSON, wrong shape: no top-level `media` array.
        let result = parse_table(r#"{"$comment": "no media field here"}"#);
        assert!(
            result.is_err(),
            "JSON missing the `media` array must be refused"
        );
    }

    #[test]
    fn well_formed_json_parses_through_the_same_path_the_shipped_table_uses() {
        let json = r#"{"media": [{"md5": "0123456789abcdef0123456789abcdef", "version": "3.2", "volume": "Workbench3_2", "name": "Test Disk", "source": "test", "sequence": null}]}"#;
        let rows = parse_table(json).expect("well-formed JSON must parse");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].volume, "Workbench3_2");
    }

    // -- The outside check: this table against real media (§4.2 of the
    // design). Sibling of `scripts/media-table-check.py`, and the Rust half
    // of the pattern `core/amigaicon`'s
    // `round_trip_every_icon_in_a_folder_when_asked` established: the same
    // lookup, exercised through `core`'s own public API rather than the
    // Python script's independent re-implementation, so a mistake shared
    // between this module's reader and the shipped JSON cannot hide behind
    // agreement with itself. Needs media ART must never ship, so it is
    // `#[ignore]`d and reads its directory from `ART_MEDIA_DIR` rather than
    // a fixture — never in CI, same reason `ART_ICON_DIR`'s test is not.

    /// Every `.adf`/`.iso`/`.lha` file under `dir`, recursively — the same
    /// extensions `scripts/media-table-check.py` looks for. Read-only:
    /// `std::fs::read_dir` only lists entries.
    fn collect_media_files(dir: &std::path::Path, out: &mut Vec<std::path::PathBuf>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_media_files(&path, out);
            } else if path.extension().is_some_and(|ext| {
                let ext = ext.to_ascii_lowercase();
                ext == "adf" || ext == "iso" || ext == "lha"
            }) {
                out.push(path);
            }
        }
    }

    /// The standing measurement (2026-09-06), against the owner's own
    /// `E:\amiga\Amigatolon\paketler\3.2\AmigaOs 3.2\ADF`: 35 files, all 35
    /// hashing to a row in the shipped table, to the right `name` and the
    /// right `source` (`Hyperion (3.2 base)`), 151 of the table's 186 rows
    /// left unverified (rows the owner does not happen to own a copy of —
    /// expected, and never a failure) and 0 conflicting.
    ///
    /// Three outcomes, kept distinct per this project's own named failure
    /// class (a confident wrong sentence): **verified** (a file here hashes
    /// to this row, via [`row_for`] — the exact function
    /// `commands/`-layer code would call), **unverified** (no file here
    /// does — reported, never asserted, since it says nothing about
    /// whether the row is right), and **conflicting** (a real defect: the
    /// same file's hash resolves to more than one row, which can only
    /// happen if the shipped table itself carries a duplicate `md5` —
    /// something `every_md5_in_the_adopted_table_is_distinct` above already
    /// asserts never happens, checked again here independently, against
    /// [`rows`] rather than trusted from that other test). `unverified` is
    /// printed and never asserted on.
    ///
    /// # What it asserts, and why it used to assert nothing
    ///
    /// The first version of this test failed only on `conflicting`, which the
    /// shipped table's own invariant test already rules out — so it **passed
    /// with 0 verified**, the one result that means the table and the reader
    /// no longer agree at all. *A test is not a guard until the defect has
    /// been put back and seen to fail it*, and this one could not fail on the
    /// thing it exists to check. Two assertions now, deliberately of
    /// different kinds:
    ///
    /// - **At least one row verifies.** `ART_MEDIA_DIR` was set, so the
    ///   caller says that folder holds install media; zero matches is what a
    ///   broken lookup, a renamed field or an emptied table all produce. This
    ///   is `scripts/rom-table-check.py --scan`'s own condition (it returns
    ///   its hit count, so "no ROM identified" is exit 1).
    /// - **`ART_MEDIA_EXPECT_VERIFIED`, when set, is held to exactly.** A
    ///   specific number is a claim about specific media, so it comes from
    ///   the caller and never from a constant here: the owner's 35 is *this
    ///   machine's* measurement against *this machine's* disks, and a user
    ///   with a 3.1 set must not meet a check that fails because their media
    ///   is not the author's. `media_hashes_confirmed.json` is where that
    ///   specific claim is recorded.
    ///
    /// No directory, no assertions — the test returns before it has anything
    /// to be right or wrong about.
    #[test]
    #[ignore = "needs a folder of the owner's own real install media"]
    fn every_real_disk_in_a_folder_is_looked_up_through_cores_own_code_when_asked() {
        let Ok(folder) = std::env::var("ART_MEDIA_DIR") else {
            return;
        };
        let mut entries = Vec::new();
        collect_media_files(std::path::Path::new(&folder), &mut entries);
        entries.sort();

        let table = shipped_rows();

        // Independent of any real file: does the shipped table itself ever
        // claim one hash for two different rows? `row_for` can only ever
        // return one match per hash, so this is the only way "one file
        // matching two rows" could actually happen — checked here against
        // the table directly, not inferred from a lookup result.
        let mut by_md5: std::collections::HashMap<&str, Vec<&MediaRow>> =
            std::collections::HashMap::new();
        for row in table {
            by_md5.entry(row.md5.as_str()).or_default().push(row);
        }
        let mut conflicting: Vec<String> = Vec::new();
        for (md5, rows_for_hash) in &by_md5 {
            if rows_for_hash.len() > 1 {
                let names: Vec<&str> = rows_for_hash.iter().map(|r| r.name.as_str()).collect();
                conflicting.push(format!(
                    "{md5} is claimed by {} rows: {}",
                    rows_for_hash.len(),
                    names.join(", ")
                ));
            }
        }

        let mut checked = 0usize;
        let mut not_in_table = 0usize;
        let mut matched_md5: std::collections::HashSet<String> = std::collections::HashSet::new();
        for entry in &entries {
            let hash = match crate::core::hashing::md5_file(entry) {
                Ok(h) => h,
                Err(err) => {
                    println!("ART_MEDIA_UNREADABLE {}: {err}", entry.display());
                    continue;
                }
            };
            checked += 1;
            match row_for(&hash) {
                Ok(Some(row)) => {
                    matched_md5.insert(row.md5.clone());
                    println!(
                        "ART_MEDIA_MATCH {}: {} ({}, {})",
                        entry.display(),
                        row.name,
                        row.version,
                        row.source
                    );
                }
                Ok(None) => {
                    // No row claims this file. Says nothing about the
                    // file's identity (§4.3 of the design) — reported, not
                    // a failure.
                    not_in_table += 1;
                }
                Err(err) => {
                    conflicting.push(format!("row_for({hash}) for {}: {err}", entry.display()));
                }
            }
        }

        let verified = table
            .iter()
            .filter(|r| matched_md5.contains(&r.md5))
            .count();
        let unverified = table.len() - verified;

        println!(
            "ART_MEDIA_RESULT checked={checked} not_in_table={not_in_table} verified={verified} unverified={unverified} conflicting={}",
            conflicting.len()
        );
        for c in &conflicting {
            println!("ART_MEDIA_CONFLICT {c}");
        }

        assert!(
            conflicting.is_empty(),
            "{} conflicting row(s) — see ART_MEDIA_CONFLICT lines above",
            conflicting.len()
        );

        // The assertion that makes this a guard rather than a printout.
        assert!(
            verified > 0,
            "no row in the shipped table verified against anything in {folder}: \
             {checked} file(s) were hashed and none of them matched a row. Either that \
             folder does not hold install media, or the table and the reader no longer \
             agree — which is the whole reason this test exists"
        );

        // And the caller's own number, when the caller states one. Never a
        // constant here: 35 is the owner's measurement of the owner's disks.
        if let Ok(expected) = std::env::var("ART_MEDIA_EXPECT_VERIFIED") {
            let expected: usize = expected
                .trim()
                .parse()
                .expect("ART_MEDIA_EXPECT_VERIFIED must be a whole number");
            assert_eq!(
                verified, expected,
                "expected exactly {expected} verified row(s) against {folder}, got {verified} — \
                 a difference here is a finding to report, not a number to adjust"
            );
        }
    }

    // -- Identifying a folder (the module's second half).

    use crate::core::jobs::CancelToken;
    use crate::core::osinstall::fixtures;
    use crate::core::ScratchDir;
    use std::sync::Mutex;

    /// A sink that records every report and can be told to cancel after a
    /// given number of them — so "stopped between whole files" is asserted
    /// against a specific file, not against a stopwatch (CLAUDE.md: anything
    /// timing-dependent gets an invariant, not a wait).
    struct CancelAfter {
        reports: Mutex<Vec<(u64, Option<u64>, String)>>,
        cancel_after: usize,
        token: CancelToken,
    }

    impl CancelAfter {
        fn new(cancel_after: usize) -> Self {
            Self {
                reports: Mutex::new(Vec::new()),
                cancel_after,
                token: CancelToken::new(),
            }
        }
        fn never() -> Self {
            Self::new(usize::MAX)
        }
        fn reports(&self) -> Vec<(u64, Option<u64>, String)> {
            self.reports.lock().unwrap().clone()
        }
    }

    impl ProgressSink for CancelAfter {
        fn report(&self, done: u64, total: Option<u64>, message: &str) {
            let mut reports = self.reports.lock().unwrap();
            reports.push((done, total, message.to_string()));
            // Counted in reports, not in files: report number 1 is the
            // 0-of-N one sent before anything is read, so `2` here means
            // "cancel once the first file has been finished and reported".
            if reports.len() >= self.cancel_after {
                self.token.cancel();
            }
        }
        fn is_cancelled(&self) -> bool {
            self.token.is_cancelled()
        }
    }

    /// Three synthetic disks and somewhere to cache what is learnt about
    /// them. Synthetic and built at run time — ART ships no Amiga content.
    fn folder_of_media(tag: &str) -> (ScratchDir, PathBuf, ScanCache, Vec<PathBuf>) {
        let dir = ScratchDir::new("art-mediahash", tag);
        let media = dir.join("media");
        std::fs::create_dir_all(&media).unwrap();
        let disks = vec![
            fixtures::media(
                &media,
                "Workbench3.2",
                "a-wb.adf",
                &[("C/LoadModule", b"cmd", 0x20)],
            ),
            fixtures::media(
                &media,
                "Locale-DE",
                "b-locale.adf",
                &[("Catalogs/x", b"cat", 0x20)],
            ),
            fixtures::media(
                &media,
                "Storage3.2",
                "c-storage.adf",
                &[("Monitors/y", b"mon", 0x20)],
            ),
        ];
        let cache_dir = dir.join("cache");
        std::fs::create_dir_all(&cache_dir).unwrap();
        (dir, media, ScanCache::in_dir(cache_dir), disks)
    }

    /// **The join, against a hash that really is in the table.**
    ///
    /// No synthetic fixture can ever hash to a shipped row — that would need
    /// an MD5 preimage — so the join is exercised directly with a real
    /// row's key. Deliberately the `Backdrops3_2` row, because it is one of
    /// the twelve the 2026-09-06 measurement was taken on: the table calls
    /// that disk `Backdrops3_2` and the disk's own root block calls itself
    /// `Backdrops3.2`. Both come back, unchanged and unreconciled.
    #[test]
    fn a_match_carries_the_disks_own_name_and_the_tables_name_as_two_separate_facts() {
        let row = shipped_rows()
            .iter()
            .find(|r| r.volume == "Backdrops3_2")
            .expect("the shipped table carries the Backdrops 3.2 row");

        let found = match_for(
            Path::new("E:\\amiga\\Backdrops3.2.adf"),
            Some("Backdrops3.2".to_string()),
            row.md5.clone(),
        )
        .expect("the shipped table must parse");

        let matched = found.row.as_ref().expect("this hash is in the table");
        assert_eq!(matched.volume, "Backdrops3_2", "the table's own identifier");
        assert_eq!(
            found.volume_name.as_deref(),
            Some("Backdrops3.2"),
            "the disk's own root block, untouched by the lookup"
        );
        assert_ne!(
            matched.volume,
            found.volume_name.clone().unwrap(),
            "these are two namespaces; measured 2026-09-06 as 0 of 12 matching, and \
             nothing may join them"
        );
        assert_eq!(matched.name, row.name);
        assert_eq!(matched.source, row.source);
        assert_eq!(matched.version, row.version);
    }

    /// **A match carries whether the row was ever checked here, and the two
    /// answers are different objects, not one shared default.**
    ///
    /// Both arms in one test on purpose: the guard is the *difference*. A
    /// `confirmed` field that were always `Some` would pass a
    /// confirmed-only test, and one that were always `None` would pass an
    /// unconfirmed-only test; only asking both of a real confirmed row and a
    /// real unconfirmed one can fail either way.
    #[test]
    fn a_match_says_whether_the_row_was_ever_checked_against_a_real_disk() {
        // Confirmed: the owner's own Workbench 3.2 disk, in the record.
        let confirmed_row = shipped_rows()
            .iter()
            .find(|r| r.md5 == "5edf0b7a10409ef992ea351565ef8b6c")
            .expect("the shipped table carries the Workbench 3.2 row");
        let confirmed = match_for(
            Path::new("E:\\amiga\\Workbench3.2.adf"),
            Some("Workbench3.2".to_string()),
            confirmed_row.md5.clone(),
        )
        .unwrap();
        let citation = confirmed
            .confirmed
            .as_ref()
            .expect("this row was checked against the owner's own disk");
        assert_eq!(citation.checked, "2026-09-06");
        assert!(citation.against.contains("AmigaOS 3.2"));

        // Unconfirmed: a row that is just as much in the table, and that
        // nobody here owns a disk for. Same shape of match, different
        // sentence.
        let unconfirmed_row = shipped_rows()
            .iter()
            .find(|r| r.source == "Escom")
            .expect("the shipped table carries Escom rows");
        let unconfirmed = match_for(
            Path::new("E:\\amiga\\someone-elses.adf"),
            Some("Workbench3.1".to_string()),
            unconfirmed_row.md5.clone(),
        )
        .unwrap();
        assert!(
            unconfirmed.row.is_some(),
            "the row must be found — this is a match, not a miss"
        );
        assert!(
            unconfirmed.confirmed.is_none(),
            "no disk here has ever confirmed this row, and the screen must not say one has"
        );
    }

    /// A miss carries no confirmation, because there is no row to have been
    /// confirmed. Asserted separately from the row being `None` so the two
    /// cannot come to disagree — a confirmation beside no row would be a
    /// claim about the disk itself.
    #[test]
    fn a_miss_carries_no_confirmation_because_there_is_no_row_to_confirm() {
        let found = match_for(
            Path::new("E:\\amiga\\mine.adf"),
            Some("Workbench3.2".to_string()),
            "00000000000000000000000000000000".to_string(),
        )
        .unwrap();
        assert!(found.row.is_none());
        assert!(found.confirmed.is_none());
    }

    /// A hash in no row is "not in the table", and it takes nothing away
    /// from what the disk already said about itself (§4.3: additive, never
    /// subtractive).
    #[test]
    fn a_hash_in_no_row_leaves_the_disks_own_name_standing() {
        let found = match_for(
            Path::new("E:\\amiga\\mine.adf"),
            Some("Workbench3.2".to_string()),
            "00000000000000000000000000000000".to_string(),
        )
        .unwrap();
        assert!(found.row.is_none(), "no row claims this hash");
        assert_eq!(
            found.volume_name.as_deref(),
            Some("Workbench3.2"),
            "a miss must not weaken what the volume name established"
        );
        assert_eq!(found.md5, "00000000000000000000000000000000");
    }

    /// The whole pass over a real folder: every candidate hashed, the hash
    /// pinned against `md5_file`'s own answer, the volume name read off the
    /// disk, and a real progress total from the very first report.
    #[test]
    fn a_folder_is_identified_file_by_file_with_a_real_total() {
        let (_dir, folder, cache, disks) = folder_of_media("folder");
        let sink = CancelAfter::never();
        let found = identify_media_in(&folder, &cache, &sink).unwrap();

        assert_eq!(found.matches.len(), 3);
        assert_eq!(found.hashed, 3);
        assert_eq!(found.remembered, 0);
        assert!(found.unreadable.is_empty());

        for (entry, disk) in found.matches.iter().zip(&disks) {
            assert_eq!(&entry.path, disk);
            assert_eq!(entry.md5, crate::core::hashing::md5_file(disk).unwrap());
            assert!(entry.row.is_none(), "a synthetic disk is in no row");
        }
        assert_eq!(
            found
                .matches
                .iter()
                .map(|m| m.volume_name.clone().unwrap())
                .collect::<Vec<_>>(),
            vec!["Workbench3.2", "Locale-DE", "Storage3.2"],
            "each disk's own root block, in path order"
        );

        let reports = sink.reports();
        assert_eq!(reports.len(), 4, "one before the first file, one per file");
        assert!(
            reports.iter().all(|(_, total, _)| *total == Some(3)),
            "the total is known before the first byte is read: {reports:?}"
        );
        assert_eq!(reports[0].0, 0);
        assert_eq!(reports[3].0, 3);
    }

    /// Only the six extensions the outside check looks at, and never a
    /// directory that happens to be named like one.
    #[test]
    fn only_media_extensions_are_candidates_and_a_directory_is_not_one() {
        let dir = ScratchDir::new("art-mediahash", "candidates");
        for name in [
            "a.adf",
            "b.ISO",
            "c.lha",
            "e.lzh",
            "f.ZIP",
            "g.7z",
            "notes.txt",
            "d.hdf",
        ] {
            std::fs::write(dir.join(name), b"x").unwrap();
        }
        std::fs::create_dir_all(dir.join("trap.adf")).unwrap();

        let names: Vec<String> = candidates_in(dir.path())
            .unwrap()
            .iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert_eq!(
            names,
            vec!["a.adf", "b.ISO", "c.lha", "e.lzh", "f.ZIP", "g.7z"]
        );
    }

    /// A folder that is not there is an error, not an empty answer — the
    /// user just named it.
    #[test]
    fn a_folder_that_cannot_be_read_is_an_error_not_an_empty_list() {
        let dir = ScratchDir::new("art-mediahash", "gone");
        assert!(candidates_in(&dir.join("nowhere")).is_err());
    }

    /// **The second pass hashes nothing, and this is a counted difference
    /// rather than an impression.**
    ///
    /// `hashed`/`remembered` go from 3/0 to 0/3 over the same folder, and
    /// the three answers are byte-identical. Both halves are asserted
    /// because `hashed == 0` on its own has a second cause — a pass that
    /// found no files at all would report it too.
    #[test]
    fn a_second_pass_over_the_same_folder_hashes_nothing() {
        let (_dir, folder, cache, _disks) = folder_of_media("counted");

        let first = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();
        assert_eq!((first.hashed, first.remembered), (3, 0));

        let second = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();
        assert_eq!(
            (second.hashed, second.remembered),
            (0, 3),
            "every hash came out of the cache"
        );
        assert_eq!(second.matches.len(), 3, "and all three were still answered");
        assert_eq!(first.matches, second.matches);
    }

    /// **…and the cached hash really is the one that is served, which the
    /// counted test alone cannot prove.**
    ///
    /// `scan_cache`'s own trap, one layer up: a cache-hit test passes even
    /// when the cache is never consulted, because re-reading the file would
    /// have produced the same answer. So the disks are overwritten with
    /// different bytes while their `(path, size, mtime)` are held exactly as
    /// they were. A re-hash would now return three different MD5s; the
    /// cache returns the original three.
    ///
    /// This is also the stale-answer arrangement `ScanCache::forget_all`
    /// exists for, and the last two lines are that escape hatch working.
    #[test]
    fn a_cached_hash_is_served_even_when_the_bytes_have_changed_underneath() {
        let (_dir, folder, cache, disks) = folder_of_media("consulted");
        let first = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();

        let mut rehashed = Vec::new();
        for disk in &disks {
            let metadata = std::fs::metadata(disk).unwrap();
            let stamp = metadata.modified().unwrap();
            std::fs::write(disk, vec![0x5au8; metadata.len() as usize]).unwrap();
            let file = std::fs::OpenOptions::new().write(true).open(disk).unwrap();
            file.set_modified(stamp).unwrap();
            file.sync_all().unwrap();
            rehashed.push(crate::core::hashing::md5_file(disk).unwrap());
        }
        for (entry, now) in first.matches.iter().zip(&rehashed) {
            assert_ne!(
                &entry.md5, now,
                "the fixture must really have different bytes now, or this proves nothing"
            );
        }

        let second = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();
        assert_eq!(
            second
                .matches
                .iter()
                .map(|m| m.md5.clone())
                .collect::<Vec<_>>(),
            first
                .matches
                .iter()
                .map(|m| m.md5.clone())
                .collect::<Vec<_>>(),
            "an answer this can only have come from the cache"
        );
        assert_eq!((second.hashed, second.remembered), (0, 3));

        // The escape hatch: after a rescan the bytes are read again.
        assert_eq!(cache.forget_all(), 3);
        let third = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();
        assert_eq!(
            third
                .matches
                .iter()
                .map(|m| m.md5.clone())
                .collect::<Vec<_>>(),
            rehashed,
            "a rescan goes back to the file"
        );
        assert_eq!((third.hashed, third.remembered), (3, 0));
    }

    /// A file whose bytes cannot be read is reported by name and costs the
    /// others nothing. Not silently skipped: a file missing from `matches`
    /// reads as a file that is not in the folder, which is a different and
    /// untrue sentence.
    #[test]
    fn a_file_that_cannot_be_read_is_reported_and_the_rest_still_run() {
        let (_dir, folder, cache, disks) = folder_of_media("unreadable");
        let locked = &disks[1];
        let _guard = deny_reads(locked);
        assert!(
            std::fs::read(locked).is_err(),
            "the fixture must genuinely be unreadable, or this test proves nothing"
        );

        let found = identify_media_in(&folder, &cache, &CancelAfter::never()).unwrap();
        assert_eq!(found.unreadable, vec![locked.clone()]);
        assert_eq!(found.matches.len(), 2);
        assert_eq!(found.hashed, 2);
        assert!(
            found.matches.iter().all(|m| &m.path != locked),
            "an unreadable file has no hash and so no match"
        );
        assert!(
            cache.lookup_md5(locked).is_none(),
            "and nothing was recorded about it"
        );
    }

    /// **Cancelling stops between whole files and leaves nothing
    /// half-written.**
    ///
    /// The sink cancels after the first file's report, so the second file's
    /// check is the one that trips. Asserted three ways, because "the third
    /// disk has no cache entry" alone has a second cause (a `store_md5` that
    /// never worked at all): the first disk's entry is present *and*
    /// correct, the later ones are absent, the cache directory holds nothing
    /// but well-formed entries, and every disk is byte-for-byte what it was.
    #[test]
    fn cancelling_stops_between_files_and_leaves_nothing_half_written() {
        let (_dir, folder, cache, disks) = folder_of_media("cancel");
        let before: Vec<Vec<u8>> = disks.iter().map(|d| std::fs::read(d).unwrap()).collect();

        // Cancel the moment the first file has been hashed and reported, so
        // the *second* file's check is the one that trips.
        let sink = CancelAfter::new(2);
        let outcome = identify_media_in(&folder, &cache, &sink);
        let Err(err) = &outcome else {
            panic!("cancelling must stop the pass; instead it ran every file to the end");
        };
        assert!(
            matches!(err, CoreError::Cancelled),
            "stopping because the user asked is not a failure, it is {err:?}"
        );

        assert_eq!(
            cache.lookup_md5(&disks[0]),
            Some(crate::core::hashing::md5_file(&disks[0]).unwrap()),
            "the file it finished is recorded, and recorded correctly"
        );
        assert_eq!(
            cache.lookup_md5(&disks[1]),
            None,
            "it stopped before this one"
        );
        assert_eq!(cache.lookup_md5(&disks[2]), None);

        let ScanCache::In(cache_dir) = &cache else {
            unreachable!()
        };
        let entries: Vec<PathBuf> = std::fs::read_dir(cache_dir)
            .unwrap()
            .flatten()
            .map(|e| e.path())
            .collect();
        assert_eq!(
            entries.len(),
            1,
            "one entry, no half-written strays: {entries:?}"
        );
        assert!(
            serde_json::from_slice::<serde_json::Value>(&std::fs::read(&entries[0]).unwrap())
                .is_ok(),
            "and it is whole"
        );

        for (disk, was) in disks.iter().zip(&before) {
            assert_eq!(
                &std::fs::read(disk).unwrap(),
                was,
                "{} was written to",
                disk.display()
            );
        }
    }

    /// Hold `path` open in a way that makes reading it fail, for as long as
    /// the returned guard lives.
    ///
    /// Test-only, and platform-specific because "unreadable" is: Windows has
    /// no read permission bit that applies to the file's owner, and Unix has
    /// no exclusive share mode. `core/` itself stays platform-independent —
    /// nothing outside `#[cfg(test)]` here touches either.
    #[cfg(windows)]
    fn deny_reads(path: &Path) -> std::fs::File {
        use std::os::windows::fs::OpenOptionsExt;
        std::fs::OpenOptions::new()
            .write(true)
            .share_mode(0) // no FILE_SHARE_READ: nothing else may open it
            .open(path)
            .expect("the fixture exists")
    }

    #[cfg(not(windows))]
    fn deny_reads(path: &Path) {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o000))
            .expect("the fixture exists");
    }

    #[test]
    fn a_parse_failure_is_cached_not_reparsed_on_the_second_call() {
        // Exercises `cached` directly against a private `OnceLock`, so this
        // never touches the process-wide table every other caller shares
        // (the shipped JSON always parses, so that one never holds an error
        // in this test binary).
        //
        // The second call passes *different* malformed JSON than the first.
        // If the caching arrangement in `table()` were broken — reparsing on
        // every call instead of serving the cached result — the second call
        // would parse the second string on its own and very likely report a
        // different `serde_json` error (different text, different byte
        // offset). Getting the *first* call's exact error back on the
        // second call is only possible if the cache, not a fresh parse,
        // answered it — which is the specific guarantee this arrangement
        // exists to give `row_for`/`rows` callers.
        static CACHE: OnceLock<Result<Vec<MediaRow>, String>> = OnceLock::new();
        let first = cached(
            &CACHE,
            "not json at all",
            "install-media hash table",
            parse_table,
        )
        .unwrap_err();
        let second = cached(
            &CACHE,
            "{{{ this is a completely different malformed document",
            "install-media hash table",
            parse_table,
        )
        .unwrap_err();
        assert_eq!(
            format!("{first}"),
            format!("{second}"),
            "the second call must return the first call's cached error, not a fresh parse \
             of the second (different) input"
        );
    }
}
