//! Operation Log — an auditable record of everything ART did to a user's data.
//!
//! Spec §53 requires every significant operation to produce a structured entry,
//! and §68 requires errors to carry an identifier rather than an opaque code.
//! The log is where both land, and it is the trail §45.5.8 will need when plans
//! start coming from an AI (`origin: ai-plan`).
//!
//! Two rules shape the design:
//!
//! - **Logging never fails an operation.** A full disk or a locked file must not
//!   turn a successful write into a reported failure; recording is best-effort
//!   and its own errors are surfaced separately.
//! - **The record is written after the fact.** It states what happened, not what
//!   was attempted, so a failed operation is logged as a failure with its error
//!   ID rather than silently omitted.
//!
//! Storage is append-only JSON Lines: trivially exportable (§53: "Logs can be
//! exported"), survives a crash mid-write with at most one truncated line, and
//! needs no schema migration as fields are added.

pub mod jsonl;

pub use jsonl::JsonlOperationLog;

use serde::{Deserialize, Serialize};

use crate::core::error::CoreResult;

/// Where an operation came from.
///
/// `AiPlan` exists so the AI layer (§45.5) has somewhere to declare itself from
/// the start — an operation ART performed on its own suggestion must always be
/// distinguishable from one the user asked for directly.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "origin", rename_all = "snake_case")]
pub enum OperationOrigin {
    /// The user acted in a studio.
    UserInterface,
    /// A workflow the engine offered was run.
    Workflow { workflow_id: String },
    /// A step of a plan generated by the AI layer (spec §45.5.8).
    AiPlan { plan_id: String },
}

/// How an operation ended.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "result", rename_all = "snake_case")]
pub enum OperationOutcome {
    Success {
        /// `Some(true)` = verified, `Some(false)` = verification failed,
        /// `None` = the operation has nothing to verify.
        verification: Option<bool>,
    },
    Failure {
        /// The error ID from [`crate::core::error::CoreError::code`].
        error_code: String,
        message: String,
    },
}

impl OperationOutcome {
    /// Convenience for the common "it worked, nothing to verify" case.
    pub fn success() -> Self {
        Self::Success { verification: None }
    }

    /// Success with a verification verdict.
    pub fn verified(passed: bool) -> Self {
        Self::Success {
            verification: Some(passed),
        }
    }

    pub fn is_success(&self) -> bool {
        matches!(self, Self::Success { .. })
    }
}

/// One entry in the operation log.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OperationRecord {
    /// Seconds since the Unix epoch.
    pub timestamp: u64,
    /// What was done, in the user's language: "Add file to disk".
    pub operation: String,
    pub source: Option<String>,
    pub destination: Option<String>,
    /// Where the previous version went, when the operation took a backup.
    pub backup: Option<String>,
    /// Extra facts worth keeping: `("Files", "247")`.
    pub details: Vec<(String, String)>,
    pub outcome: OperationOutcome,
    #[serde(flatten)]
    pub origin: OperationOrigin,
}

impl OperationRecord {
    /// Start a record for `operation`, stamped now.
    pub fn new(operation: impl Into<String>, origin: OperationOrigin) -> Self {
        Self {
            timestamp: now_unix(),
            operation: operation.into(),
            source: None,
            destination: None,
            backup: None,
            details: Vec::new(),
            outcome: OperationOutcome::success(),
            origin,
        }
    }

    pub fn source(mut self, path: impl Into<String>) -> Self {
        self.source = Some(path.into());
        self
    }

    pub fn destination(mut self, path: impl Into<String>) -> Self {
        self.destination = Some(path.into());
        self
    }

    pub fn backup(mut self, path: Option<String>) -> Self {
        self.backup = path;
        self
    }

    pub fn detail(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.details.push((key.into(), value.into()));
        self
    }

    pub fn outcome(mut self, outcome: OperationOutcome) -> Self {
        self.outcome = outcome;
        self
    }

    /// Record a failure straight from a core error, keeping its ID (§68).
    pub fn failed(self, error: &crate::core::error::CoreError) -> Self {
        self.failure(error.code(), error.to_string())
    }

    /// Record a failure from an error the core does not know about — the shell
    /// passes its own code and message through.
    pub fn failure(mut self, error_code: impl Into<String>, message: impl Into<String>) -> Self {
        self.outcome = OperationOutcome::Failure {
            error_code: error_code.into(),
            message: message.into(),
        };
        self
    }

    /// Render the entry in the report form the spec shows (§53).
    pub fn render(&self) -> String {
        let mut out = format!("Operation:\n{}\n", self.operation);

        if let Some(ref src) = self.source {
            out.push_str(&format!("\nSource:\n{src}\n"));
        }
        if let Some(ref dst) = self.destination {
            out.push_str(&format!("\nDestination:\n{dst}\n"));
        }
        for (key, value) in &self.details {
            out.push_str(&format!("\n{key}:\n{value}\n"));
        }
        if let Some(ref backup) = self.backup {
            out.push_str(&format!("\nBacked up to:\n{backup}\n"));
        }

        match &self.outcome {
            OperationOutcome::Success { verification } => {
                out.push_str("\nResult:\nSUCCESS\n");
                match verification {
                    Some(true) => out.push_str("\nVerification:\nPASS\n"),
                    Some(false) => out.push_str("\nVerification:\nFAILED\n\nOriginal preserved.\n"),
                    None => {}
                }
            }
            OperationOutcome::Failure {
                error_code,
                message,
            } => {
                out.push_str(&format!(
                    "\nResult:\nFAILED\n\n{message}\n\nError ID:\n{error_code}\n"
                ));
            }
        }

        out
    }
}

/// Somewhere operation records can be written.
///
/// A trait so the core stays platform-independent: it decides *what* to record,
/// while the shell decides where it lands (spec's core independence rule).
pub trait OperationLog: Send + Sync {
    /// Append a record. Implementations must not panic and should not fail the
    /// caller's operation — the return value is for diagnostics only.
    fn record(&self, record: &OperationRecord) -> CoreResult<()>;

    /// Most recent entries, newest first, at most `limit`.
    fn recent(&self, limit: usize) -> CoreResult<Vec<OperationRecord>>;
}

/// Seconds since the Unix epoch, or 0 if the clock is before it.
pub(crate) fn now_unix() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::error::CoreError;

    #[test]
    fn renders_the_spec_report_shape() {
        let record = OperationRecord::new("Install WHDLoad", OperationOrigin::UserInterface)
            .source("Game.lha")
            .destination("Games.hdf")
            .detail("Files", "247")
            .outcome(OperationOutcome::verified(true));

        let text = record.render();
        assert!(text.contains("Operation:\nInstall WHDLoad"));
        assert!(text.contains("Source:\nGame.lha"));
        assert!(text.contains("Destination:\nGames.hdf"));
        assert!(text.contains("Files:\n247"));
        assert!(text.contains("Result:\nSUCCESS"));
        assert!(text.contains("Verification:\nPASS"));
    }

    /// §58: a failed verification must say the original survived.
    #[test]
    fn failed_verification_reassures_about_the_original() {
        let record = OperationRecord::new("Resize HDF", OperationOrigin::UserInterface)
            .outcome(OperationOutcome::verified(false));

        let text = record.render();
        assert!(text.contains("Verification:\nFAILED"));
        assert!(text.contains("Original preserved."));
    }

    /// §68: a failure carries an ID the user can quote.
    #[test]
    fn failures_keep_the_error_id() {
        let err = CoreError::SafetyRefused("image already exists".into());
        let record =
            OperationRecord::new("Create hard disk", OperationOrigin::UserInterface).failed(&err);

        assert!(!record.outcome.is_success());
        let text = record.render();
        assert!(text.contains("Result:\nFAILED"));
        assert!(text.contains("image already exists"));
        assert!(text.contains("Error ID:\nART-SAFETY-REFUSED"));
    }

    #[test]
    fn origin_survives_a_round_trip() {
        for origin in [
            OperationOrigin::UserInterface,
            OperationOrigin::Workflow {
                workflow_id: "adf.validate".into(),
            },
            OperationOrigin::AiPlan {
                plan_id: "plan-1".into(),
            },
        ] {
            let record = OperationRecord::new("x", origin.clone());
            let json = serde_json::to_string(&record).unwrap();
            let back: OperationRecord = serde_json::from_str(&json).unwrap();
            assert_eq!(back.origin, origin);
        }
    }
}
